### ISSUE TITLE
Unexpected token . error about .forRoot()

### ISSUE THREAD

**Issue by realgsong** [maciejtreder/ng-toolkit#286]
## I'm submitting a...

<pre><code>
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[x] @ng-toolkit/universal
</code></pre>

## Current behavior

```
SyntaxError: Unexpected token . in JSON at position 1016
    at JSON.parse (<anonymous>)
    at Object.getDecoratorSettings (/home/gsong/poclcast/poclweb/node_modules/@ng-toolkit/_utils/index.js:378:21)
    at _utils_1.applyAndLog.schematics_1.chain (/home/gsong/poclcast/poclweb/node_modules/@ng-toolkit/universal/src/index.js:66:51)
    at MergeMapSubscriber.input.pipe.operators_1.mergeMap.inputTree [as project] (/home/gsong/poclcast/poclweb/node_modules/@angular-devkit/schematics/src/rules/call.js:77:24)
    at MergeMapSubscriber._tryNext (/home/gsong/poclcast/poclweb/node_modules/rxjs/internal/operators/mergeMap.js:122:27)
    at MergeMapSubscriber._next (/home/gsong/poclcast/poclweb/node_modules/rxjs/internal/operators/mergeMap.js:112:18)
    at MergeMapSubscriber.Subscriber.next (/home/gsong/poclcast/poclweb/node_modules/rxjs/internal/Subscriber.js:103:18)
    at MergeMapSubscriber.notifyNext (/home/gsong/poclcast/poclweb/node_modules/rxjs/internal/operators/mergeMap.js:141:26)
    at InnerSubscriber._next (/home/gsong/poclcast/poclweb/node_modules/rxjs/internal/InnerSubscriber.js:30:21)
    at InnerSubscriber.Subscriber.next (/home/gsong/poclcast/poclweb/node_modules/rxjs/internal/Subscriber.js:103:18)
    at TapSubscriber._next (/home/gsong/poclcast/poclweb/node_modules/rxjs/internal/operators/tap.js:109:26)
    at TapSubscriber.Subscriber.next (/home/gsong/poclcast/poclweb/node_modules/rxjs/internal/Subscriber.js:103:18)
    at TapSubscriber._next (/home/gsong/poclcast/poclweb/node_modules/rxjs/internal/operators/tap.js:109:26)
    at TapSubscriber.Subscriber.next (/home/gsong/poclcast/poclweb/node_modules/rxjs/internal/Subscriber.js:103:18)
    at TakeLastSubscriber._complete (/home/gsong/poclcast/poclweb/node_modules/rxjs/internal/operators/takeLast.js:109:29)
    at TakeLastSubscriber.Subscriber.complete (/home/gsong/poclcast/poclweb/node_modules/rxjs/internal/Subscriber.js:128:18)
    at MapSubscriber.Subscriber._complete (/home/gsong/poclcast/poclweb/node_modules/rxjs/internal/Subscriber.js:146:26)
    at MapSubscriber.Subscriber.complete (/home/gsong/poclcast/poclweb/node_modules/rxjs/internal/Subscriber.js:128:18)
    at TapSubscriber._complete (/home/gsong/poclcast/poclweb/node_modules/rxjs/internal/operators/tap.js:129:33)
    at TapSubscriber.Subscriber.complete (/home/gsong/poclcast/poclweb/node_modules/rxjs/internal/Subscriber.js:128:18)
    at TapSubscriber._complete (/home/gsong/poclcast/poclweb/node_modules/rxjs/internal/operators/tap.js:129:33)
    at TapSubscriber.Subscriber.complete (/home/gsong/poclcast/poclweb/node_modules/rxjs/internal/Subscriber.js:128:18)
    at TakeLastSubscriber._complete (/home/gsong/poclcast/poclweb/node_modules/rxjs/internal/operators/takeLast.js:112:21)
    at TakeLastSubscriber.Subscriber.complete (/home/gsong/poclcast/poclweb/node_modules/rxjs/internal/Subscriber.js:128:18)
    at MergeMapSubscriber._complete (/home/gsong/poclcast/poclweb/node_modules/rxjs/internal/operators/mergeMap.js:137:30)
    at MergeMapSubscriber.Subscriber.complete (/home/gsong/poclcast/poclweb/node_modules/rxjs/internal/Subscriber.js:128:18)
    at Observable._subscribe (/home/gsong/poclcast/poclweb/node_modules/rxjs/internal/observable/scalar.js:7:20)
    at Observable.subscribe (/home/gsong/poclcast/poclweb/node_modules/rxjs/internal/Observable.js:162:69)
    at MergeMapOperator.call (/home/gsong/poclcast/poclweb/node_modules/rxjs/internal/operators/mergeMap.js:87:23)
    at Observable.subscribe (/home/gsong/poclcast/poclweb/node_modules/rxjs/internal/Observable.js:159:22)
    at TakeLastOperator.call (/home/gsong/poclcast/poclweb/node_modules/rxjs/internal/operators/takeLast.js:71:23)
    at Observable.subscribe (/home/gsong/poclcast/poclweb/node_modules/rxjs/internal/Observable.js:159:22)
    at DoOperator.call (/home/gsong/poclcast/poclweb/node_modules/rxjs/internal/operators/tap.js:71:23)
    at Observable.subscribe (/home/gsong/poclcast/poclweb/node_modules/rxjs/internal/Observable.js:159:22)
    at DoOperator.call (/home/gsong/poclcast/poclweb/node_modules/rxjs/internal/operators/tap.js:71:23)
    at Observable.subscribe (/home/gsong/poclcast/poclweb/node_modules/rxjs/internal/Observable.js:159:22)
    at MapOperator.call (/home/gsong/poclcast/poclweb/node_modules/rxjs/internal/operators/map.js:62:23)
    at Observable.subscribe (/home/gsong/poclcast/poclweb/node_modules/rxjs/internal/Observable.js:159:22)
    at TakeLastOperator.call (/home/gsong/poclcast/poclweb/node_modules/rxjs/internal/operators/takeLast.js:71:23)
    at Observable.subscribe (/home/gsong/poclcast/poclweb/node_modules/rxjs/internal/Observable.js:159:22)
    at DoOperator.call (/home/gsong/poclcast/poclweb/node_modules/rxjs/internal/operators/tap.js:71:23)
    at Observable.subscribe (/home/gsong/poclcast/poclweb/node_modules/rxjs/internal/Observable.js:159:22)
    at DoOperator.call (/home/gsong/poclcast/poclweb/node_modules/rxjs/internal/operators/tap.js:71:23)
    at Observable.subscribe (/home/gsong/poclcast/poclweb/node_modules/rxjs/internal/Observable.js:159:22)
    at /home/gsong/poclcast/poclweb/node_modules/rxjs/internal/util/subscribeTo.js:22:31
    at Object.subscribeToResult (/home/gsong/poclcast/poclweb/node_modules/rxjs/internal/util/subscribeToResult.js:7:45)
    at MergeMapSubscriber._innerSub (/home/gsong/poclcast/poclweb/node_modules/rxjs/internal/operators/mergeMap.js:132:38)
    at MergeMapSubscriber._tryNext (/home/gsong/poclcast/poclweb/node_modules/rxjs/internal/operators/mergeMap.js:129:14)
    at MergeMapSubscriber._next (/home/gsong/poclcast/poclweb/node_modules/rxjs/internal/operators/mergeMap.js:112:18)
    at MergeMapSubscriber.Subscriber.next (/home/gsong/poclcast/poclweb/node_modules/rxjs/internal/Subscriber.js:103:18)
    at MergeMapSubscriber.notifyNext (/home/gsong/poclcast/poclweb/node_modules/rxjs/internal/operators/mergeMap.js:141:26)
    at InnerSubscriber._next (/home/gsong/poclcast/poclweb/node_modules/rxjs/internal/InnerSubscriber.js:30:21)
    at InnerSubscriber.Subscriber.next (/home/gsong/poclcast/poclweb/node_modules/rxjs/internal/Subscriber.js:103:18)
    at /home/gsong/poclcast/poclweb/node_modules/rxjs/internal/util/subscribeTo.js:17:28
    at Object.subscribeToResult (/home/gsong/poclcast/poclweb/node_modules/rxjs/internal/util/subscribeToResult.js:7:45)
    at MergeMapSubscriber._innerSub (/home/gsong/poclcast/poclweb/node_modules/rxjs/internal/operators/mergeMap.js:132:38)
    at MergeMapSubscriber._tryNext (/home/gsong/poclcast/poclweb/node_modules/rxjs/internal/operators/mergeMap.js:129:14)
    at MergeMapSubscriber._next (/home/gsong/poclcast/poclweb/node_modules/rxjs/internal/operators/mergeMap.js:112:18)
    at MergeMapSubscriber.Subscriber.next (/home/gsong/poclcast/poclweb/node_modules/rxjs/internal/Subscriber.js:103:18)
    at Observable._subscribe (/home/gsong/poclcast/poclweb/node_modules/rxjs/internal/observable/scalar.js:6:20)
    at Observable._trySubscribe (/home/gsong/poclcast/poclweb/node_modules/rxjs/internal/Observable.js:177:25)
    at Observable.subscribe (/home/gsong/poclcast/poclweb/node_modules/rxjs/internal/Observable.js:162:93)
    at MergeMapOperator.call (/home/gsong/poclcast/poclweb/node_modules/rxjs/internal/operators/mergeMap.js:87:23)
    at Observable.subscribe (/home/gsong/poclcast/poclweb/node_modules/rxjs/internal/Observable.js:159:22)
    at MergeMapOperator.call (/home/gsong/poclcast/poclweb/node_modules/rxjs/internal/operators/mergeMap.js:87:23)
    at Observable.subscribe (/home/gsong/poclcast/poclweb/node_modules/rxjs/internal/Observable.js:159:22)
    at MergeMapOperator.call (/home/gsong/poclcast/poclweb/node_modules/rxjs/internal/operators/mergeMap.js:87:23)
    at Observable.subscribe (/home/gsong/poclcast/poclweb/node_modules/rxjs/internal/Observable.js:159:22)
    at Domain.bugsnag.autoNotify (/home/gsong/poclcast/poclweb/node_modules/@ng-toolkit/_utils/index.js:412:33)
    at Domain.run (domain.js:242:14)
    at /home/gsong/poclcast/poclweb/node_modules/bugsnag/lib/bugsnag.js:298:20
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

## Expected behavior

No error

## Minimal reproduction of the problem with instructions

1. Add any module which calls forRoot() in app.module
1. ng add @ng-toolkit/universal

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by realgsong** [comment]
@maciejtreder thanks for quick fix. But I'm afraid that's not enough fix for "forRoot()" convention. Because parameter of forroot is very variant. some module uses object {}, some uses array []. Is there any other feasible solution not to use regex?

**Comment by maciejtreder** [comment]
Yeah. That was too enthusiastic. Right now thinking about new regex :). I think that regex would be best. Cause only thing which I want to do in this method is to JSON.parse - to make easier work with NgModule config in other functions.

**Comment by maciejtreder** [comment]
Now it should work. Checked with the following <pre>@NgModule</pre>:
```
@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
        SomeModule.forRoot(),
        OtherModule.forChild({
                "something": "someValue",
                'anotherThing': 'anotherValue'
        })
  ],
  providers: [],
  bootstrap: [AppComponent]
})
```

**Comment by maciejtreder** [comment]
Can you verify now? The build just passed.

**Comment by realgsong** [comment]
I'll check and post the result soon. Thanks for super fast fix.

**Comment by maciejtreder** [comment]
You are welcome!
🥇 star the project!
🥇 share with your friends!
🥇 support it in any way you want: https://www.angular-universal-pwa.maciejtreder.com/donors

**Comment by maciejtreder** [comment]
Ahh, and if something will still fail. Feel free to reopen this bug :)

**Comment by realgsong** [comment]
I confirmed that this error has been fixed. Thx.

**Comment by maciejtreder** [comment]
@realgsong Great! Again, thanks for your report :)
