### ISSUE TITLE
TypeError: Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by anantanandgupta** [maciejtreder/ng-toolkit#311]
## I'm submitting a...

<pre><code>
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[x] @ng-toolkit/universal
</code></pre>

## Current behavior

i have imported the @ng-toolkit/universal into my small project, built for prod and ran the server. No issue till now. Open the browser and access the server and bam!! ... console throws the below error and web page shows '{}' empty json object:

TypeError: Cannot read property 'match' of undefined
    at new AppComponent (/Users/anantanandgupta/Documents/github/CorpWebNG/dist/server.js:121840:33)
    at createClass (/Users/anantanandgupta/Documents/github/CorpWebNG/dist/server.js:10502:20)
    at createDirectiveInstance (/Users/anantanandgupta/Documents/github/CorpWebNG/dist/server.js:10385:20)
    at createViewNodes (/Users/anantanandgupta/Documents/github/CorpWebNG/dist/server.js:11607:36)
    at createRootView (/Users/anantanandgupta/Documents/github/CorpWebNG/dist/server.js:11521:5)
    at Object.createProdRootView [as createRootView] (/Users/anantanandgupta/Documents/github/CorpWebNG/dist/server.js:12037:12)
    at ComponentFactory_.module.exports.ComponentFactory_.create (/Users/anantanandgupta/Documents/github/CorpWebNG/dist/server.js:9865:29)
    at ComponentFactoryBoundToModule.module.exports.ComponentFactoryBoundToModule.create (/Users/anantanandgupta/Documents/github/CorpWebNG/dist/server.js:3841:29)
    at ApplicationRef.module.exports.ApplicationRef.bootstrap (/Users/anantanandgupta/Documents/github/CorpWebNG/dist/server.js:5387:40)
    at /Users/anantanandgupta/Documents/github/CorpWebNG/dist/server.js:5148:81

## Example repository
Sorry can't share the code as it is private repository.

## Environment

<pre><code>
Angular version: 6.0.3

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.11.1 
- Platform:  Mac

Others:

</code></pre>

**Comment by anantanandgupta** [comment]
ok it seems that this issue is related to the @ngx-translate module being part of the project and this library is not supporting the translation module at the server side. rolling back
