### ISSUE TITLE
ERROR: Browser build not found (lack of entry with build-angular:browser builder) in angular.json

### ISSUE THREAD

**Issue by noiissyboy** [maciejtreder/ng-toolkit#317]
## I'm submitting a...

<pre><code>
[*] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[*] @ng-toolkit/universal
</code></pre>

## Current behavior

+ @ng-toolkit/universal@1.1.16
added 44 packages in 49.943s
Installed packages for tooling via npm.
ERROR: Browser build not found (lack of entry with build-angular:browser builder) in angular.json

## Environment

<pre><code>
Angular version: X.Y.Z

Angular: 6.0.0, Angular CLI: 6.0.1

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
Node: 10.1.0
- Platform:  
Cent OS 7  "3.10.0-862.3.2.el7.x86_64"

Others:

</code></pre>

**Comment by maciejtreder** [comment]
@noiissyboy Could you provide some more description? Link to your repository would be more than welcome! :)

**Comment by maciejtreder** [comment]
@noiissyboy I just reproduced your issue and going to fix it. The problem is related to the 'default' project. I don't know why but Angular CLI points that `genome-biology2018-e2e` is the default one...


As a workaround, you can run schematics and explicitly point your project.

```
ng add @ng-toolkit/universal --project genome-biology2018
```

**Comment by maciejtreder** [comment]
@noiissyboy Could you verify with the latest build 1.1.18? Please, try again:

```
ng add @ng-toolkit/universal
```
on your project

**Comment by noiissyboy** [comment]
i tried "ng add @ng-toolkit/universal" added successfully to my project but when i build i got the below error "ng build --prod --base-href="http://biochem.iisc.ernet.in/GenomeBiology2018/"
 95% emitting index-html-webpack-pluginEACCES: permission denied, mkdir '/browser'      
Error: EACCES: permission denied, mkdir '/browser'"

**Comment by noiissyboy** [comment]
after successful installation of "ng add @ng-toolkit/universal" version 1.1.18, I got the below error upon command "ng serve"
ERROR in src/app/app.server.module.ts(5,55): error TS2307: Cannot find module '@angular/platform-server'.
src/app/app.server.module.ts(6,37): error TS2307: Cannot find module '@nguniversal/module-map-ngfactory-loader'.
****************************************************************************************************
and command ng build --dist brought the below error

EACCES: permission denied, rmdir '/browser'
Error: EACCES: permission denied, rmdir '/browser'
    at Object.fs.rmdirSync (fs.js:803:3)
    at MergeMapSubscriber.isDirectory.pipe.operators_1.concatMap.isDir [as project] (/home/patrick-d-silva/Projects/angular/genomeBiology2018/node_modules/@angular-devkit/core/node/host.js:173:20)
    at MergeMapSubscriber._tryNext (/home/patrick-d-silva/Projects/angular/genomeBiology2018/node_modules/rxjs/internal/operators/mergeMap.js:122:27)
    at MergeMapSubscriber._next (/home/patrick-d-silva/Projects/angular/genomeBiology2018/node_modules/rxjs/internal/operators/mergeMap.js:112:18)
    at MergeMapSubscriber.Subscriber.next (/home/patrick-d-silva/Projects/angular/genomeBiology2018/node_modules/rxjs/internal/Subscriber.js:103:18)
    at MapSubscriber._next (/home/patrick-d-silva/Projects/angular/genomeBiology2018/node_modules/rxjs/internal/operators/map.js:92:26)
    at MapSubscriber.Subscriber.next (/home/patrick-d-silva/Projects/angular/genomeBiology2018/node_modules/rxjs/internal/Subscriber.js:103:18)
    at Observable.rxjs_1.Observable.obs [as _subscribe] (/home/patrick-d-silva/Projects/angular/genomeBiology2018/node_modules/@angular-devkit/core/node/host.js:212:17)
    at Observable.subscribe (/home/patrick-d-silva/Projects/angular/genomeBiology2018/node_modules/rxjs/internal/Observable.js:162:69)
    at MapOperator.call (/home/patrick-d-silva/Projects/angular/genomeBiology2018/node_modules/rxjs/internal/operators/map.js:62:23)
    at Observable.subscribe (/home/patrick-d-silva/Projects/angular/genomeBiology2018/node_modules/rxjs/internal/Observable.js:159:22)
    at MergeMapOperator.call (/home/patrick-d-silva/Projects/angular/genomeBiology2018/node_modules/rxjs/internal/operators/mergeMap.js:87:23)
    at Observable.subscribe (/home/patrick-d-silva/Projects/angular/genomeBiology2018/node_modules/rxjs/internal/Observable.js:159:22)
    at /home/patrick-d-silva/Projects/angular/genomeBiology2018/node_modules/rxjs/internal/util/subscribeTo.js:22:31
    at Object.subscribeToResult (/home/patrick-d-silva/Projects/angular/genomeBiology2018/node_modules/rxjs/internal/util/subscribeToResult.js:7:45)
    at MergeMapSubscriber._innerSub (/home/patrick-d-silva/Projects/angular/genomeBiology2018/node_modules/rxjs/internal/operators/mergeMap.js:132:38)
***********************************************************************
after installing '@angular/platform-server' '@nguniversal/module-map-ngfactory-loader'. it got rid of the above error. but when i try "ng build dist" I got the below error

Local workspace file ('angular.json') could not be found.
Error: Local workspace file ('angular.json') could not be found.
    at WorkspaceLoader._getProjectWorkspaceFilePath (/usr/lib/node_modules/@angular/cli/models/workspace-loader.js:37:19)
    at WorkspaceLoader.loadWorkspace (/usr/lib/node_modules/@angular/cli/models/workspace-loader.js:24:21)
    at BuildCommand._loadWorkspaceAndArchitect (/usr/lib/node_modules/@angular/cli/models/architect-command.js:180:32)
    at BuildCommand.<anonymous> (/usr/lib/node_modules/@angular/cli/models/architect-command.js:47:25)
    at Generator.next (<anonymous>)
    at /usr/lib/node_modules/@angular/cli/models/architect-command.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/lib/node_modules/@angular/cli/models/architect-command.js:3:12)
    at BuildCommand.initialize (/usr/lib/node_modules/@angular/cli/models/architect-command.js:46:16)
    at Object.<anonymous> (/usr/lib/node_modules/@angular/cli/models/command-runner.js:87:23)



> ng add @ng-toolkit/universal

**Comment by maciejtreder** [comment]
Did you push changes to your repo? Ill try to take a look at ti.

**Comment by aminghe** [comment]
hi
my problem is:

INFO: Project property is set to 'hand-gate'.
ERROR: Browser build not found (lack of entry with build-angular:browser builder) in angular.json
ERROR: If you think that this error shouldn't occur, please fill up bug report here: https://github.com/maciejtreder/ng-toolkit/issues/new

angular.json:
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "newProjectRoot": "projects",
  "projects": {
    "hand-gate": {
      "root": "",
      "sourceRoot": "src",
      "projectType": "application",
      "targets": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "dist",
            "index": "src/index.html",
            "main": "src/main.ts",
            "tsConfig": "src/tsconfig.app.json",
            "polyfills": "src/polyfills.ts",
            "assets": [
              "src/assets",
              "src/favicon.ico"
            ],
            "styles": [
              "src/styles.less"
            ],
            "scripts": [
              "node_modules/jquery/dist/jquery.min.js",
              "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js",
              "src/assets/lib/jQuery.countdownTimer/jQuery.countdownTimer.min.js",
              "node_modules/swiper/dist/js/swiper.js"
            ]
          },
          "configurations": {
            "production": {
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true,
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ]
            }
          }
        },
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "browserTarget": "hand-gate:build"
          },
          "configurations": {
            "production": {
              "browserTarget": "hand-gate:build:production"
            }
          }
        },
        "extract-i18n": {
          "builder": "@angular-devkit/build-angular:extract-i18n",
          "options": {
            "browserTarget": "hand-gate:build"
          }
        },
        "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "main": "src/test.ts",
            "karmaConfig": "./karma.conf.js",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "src/tsconfig.spec.json",
            "scripts": [
              "node_modules/jquery/dist/jquery.min.js",
              "node_modules/bootstrap/dist/js/bootstrap.min.js",
              "src/assets/lib/jQuery.countdownTimer/jQuery.countdownTimer.min.js",
              "node_modules/swiper/dist/js/swiper.js"
            ],
            "styles": [
              "node_modules/bootstrap/dist/css/bootstrap.min.css",
              "node_modules/font-awesome/css/font-awesome.css",
              "src/assets/fonts/WebFonts/css/fontiran.css",
              "src/styles.less",
              "src/assets/css/main.css",
              "node_modules/swiper/dist/css/swiper.css"
            ],
            "assets": [
              "src/assets",
              "src/favicon.ico"
            ]
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": [
              "src/tsconfig.app.json",
              "src/tsconfig.spec.json"
            ],
            "exclude": []
          }
        }
      }
    },
    "hand-gate-e2e": {
      "root": "e2e",
      "sourceRoot": "e2e",
      "projectType": "application",
      "targets": {
        "e2e": {
          "builder": "@angular-devkit/build-angular:protractor",
          "options": {
            "protractorConfig": "./protractor.conf.js",
            "devServerTarget": "hand-gate:serve"
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": [
              "e2e/tsconfig.e2e.json"
            ],
            "exclude": []
          }
        }
      }
    }
  },
  "defaultProject": "hand-gate",
  "schematics": {
    "@schematics/angular:component": {
      "prefix": "app",
      "styleext": "less"
    },
    "@schematics/angular:directive": {
      "prefix": "app"
    }
  }
}

**Comment by aminghe** [comment]
I'm upgraded angular5->6 today
