### ISSUE TITLE
Error parsing triggers: Cannot find module './dist/server

### ISSUE THREAD

**Issue by ribalnasr** [maciejtreder/ng-toolkit#324]
## I'm submitting a...

<pre><code>
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[x] @ng-toolkit/serverless
[ ] @ng-toolkit/universal
</code></pre>

## Current behavior
<pre><code>
i  deploying functions, hosting
i  functions: ensuring necessary APIs are enabled...
✔  functions: all necessary APIs are enabled
i  functions: preparing functions directory for uploading...
Error: Error parsing triggers: Cannot find module './dist/server'
</code></pre>

## Expected behavior
Successful build and deploy to firebase.

## Minimal reproduction of the problem with instructions
```
$ npm i
$ ng add @ng-toolkit/serverless --provider firebase --firebaseProject slisor-test
$ npm run build:prod:deploy
```
## Example repository
https://github.com/ribalnasr/slisor

## Environment

<pre><code>
- Angular version: 6.0.8
- Node version: 8.11.2
- Platform:  Mac

**Comment by maciejtreder** [comment]
Please verify with the latest build.

**Comment by maciejtreder** [comment]
@ribalnasr And...? Any news? BTW I like the font shadows on this page ;)

**Comment by ribalnasr** [comment]
sadly no good news.
am getting this after running ng add @ng-toolkit/serverless...

added 9 packages in 6.995s
Installed packages for tooling via npm.
Cannot find module '/Users/Ribal/GitHub/slisor/node_modules/@ng-toolkit/serverless/src'
Error: Cannot find module '/Users/Ribal/GitHub/slisor/node_modules/@ng-toolkit/serverless/src'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.resolve (internal/module.js:18:19)
    at new ExportStringRef (/Users/Ribal/GitHub/slisor/node_modules/@angular-devkit/schematics/tools/export-ref.js:15:32)
    at NodeModulesEngineHost._resolveReferenceString (/Users/Ribal/GitHub/slisor/node_modules/@angular-devkit/schematics/tools/node-module-engine-host.js:91:21)
    at NodeModulesEngineHost.createSchematicDescription (/Users/Ribal/GitHub/slisor/node_modules/@angular-devkit/schematics/tools/file-system-engine-host-base.js:167:34)
    at SchematicEngine.createSchematic (/Users/Ribal/GitHub/slisor/node_modules/@angular-devkit/schematics/src/engine/engine.js:142:38)
    at CollectionImpl.createSchematic (/Users/Ribal/GitHub/slisor/node_modules/@angular-devkit/schematics/src/engine/collection.js:12:29)
    at Object.getSchematic (/Users/Ribal/GitHub/slisor/node_modules/@angular/cli/utilities/schematics.js:36:23)
    at AddCommand.getOptions (/Users/Ribal/GitHub/slisor/node_modules/@angular/cli/models/schematic-command.js:194:40)
    at AddCommand.<anonymous> (/Users/Ribal/GitHub/slisor/node_modules/@angular/cli/commands/add.js:30:49)

**Comment by maciejtreder** [comment]
Hi. I just created a pull request to your repo:
https://github.com/ribalnasr/slisor/pull/1

**Comment by yzpaul** [comment]
I am still having this issue with the latest build
