### ISSUE TITLE
ERROR TypeError: Cannot assign to read only property 'stopImmediatePropagation' of object '[object Object]'

### ISSUE THREAD

**Issue by chrisleekr** [maciejtreder/ng-toolkit#358]
## I'm submitting a...

<pre><code>
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[X] @ng-toolkit/universal
</code></pre>

## Current behavior

I have added `@ng-tookit/universal` and build for production by executing following commands:

```shell
$ ng add @ng-toolkit/universal
$ npm run build:prod
```
Both commands were successful.

And then I ran server and when I access to http://localhost:8080, I got following errors.

```shell
$ npm run server

> backend@0.0.1 server /srv
> node local.js

Listening on: http://localhost:8080
ERROR TypeError: Cannot assign to read only property 'stopImmediatePropagation' of object '[object Object]'
    at DomEventsPlugin.module.exports.DomEventsPlugin.patchEvent (/srv/dist/server.js:47703:50)
    at new DomEventsPlugin (/srv/dist/server.js:47690:15)
    at /srv/dist/server.js:186674:1305
    at _callFactory (/srv/dist/server.js:9649:28)
    at _createProviderInstance$1 (/srv/dist/server.js:9595:26)
    at resolveNgModuleDep (/srv/dist/server.js:9558:21)
    at _createClass (/srv/dist/server.js:9622:29)
    at _createProviderInstance$1 (/srv/dist/server.js:9592:26)
    at resolveNgModuleDep (/srv/dist/server.js:9558:21)
    at _createClass (/srv/dist/server.js:9628:32)
TypeError: Cannot assign to read only property 'stopImmediatePropagation' of object '[object Object]'
    at DomEventsPlugin.module.exports.DomEventsPlugin.patchEvent (/srv/dist/server.js:47703:50)
    at new DomEventsPlugin (/srv/dist/server.js:47690:15)
    at /srv/dist/server.js:186674:1305
    at _callFactory (/srv/dist/server.js:9649:28)
    at _createProviderInstance$1 (/srv/dist/server.js:9595:26)
    at resolveNgModuleDep (/srv/dist/server.js:9558:21)
    at _createClass (/srv/dist/server.js:9622:29)
    at _createProviderInstance$1 (/srv/dist/server.js:9592:26)
    at resolveNgModuleDep (/srv/dist/server.js:9558:21)
    at _createClass (/srv/dist/server.js:9628:32)
ERROR { Error: Uncaught (in promise): TypeError: http.ɵHttpInterceptingHandler is not a constructor
TypeError: http.ɵHttpInterceptingHandler is not a constructor
    at zoneWrappedInterceptingHandler (/srv/dist/server.js:104395:23)
    at _callFactory (/srv/dist/server.js:9641:20)
    at _createProviderInstance$1 (/srv/dist/server.js:9595:26)
    at resolveNgModuleDep (/srv/dist/server.js:9558:21)
    at _createClass (/srv/dist/server.js:9620:29)
    at _createProviderInstance$1 (/srv/dist/server.js:9592:26)
    at resolveNgModuleDep (/srv/dist/server.js:9558:21)
    at _createClass (/srv/dist/server.js:9620:29)
    at _createProviderInstance$1 (/srv/dist/server.js:9592:26)
    at resolveNgModuleDep (/srv/dist/server.js:9558:21)
    at resolvePromise (/srv/dist/server.js:223174:31)
    at resolvePromise (/srv/dist/server.js:223131:17)
    at /srv/dist/server.js:223233:17
    at ZoneDelegate.module.exports.ZoneDelegate.invokeTask (/srv/dist/server.js:222781:31)
    at Object.onInvokeTask (/srv/dist/server.js:4411:33)
    at ZoneDelegate.module.exports.ZoneDelegate.invokeTask (/srv/dist/server.js:222780:36)
    at Zone.module.exports.Zone.runTask (/srv/dist/server.js:222548:47)
    at drainMicroTaskQueue (/srv/dist/server.js:222955:35)
    at module.exports.ZoneTask.invokeTask (/srv/dist/server.js:222860:21)
    at ZoneTask.invoke (/srv/dist/server.js:222845:48)
  rejection: TypeError: http.ɵHttpInterceptingHandler is not a constructor
    at zoneWrappedInterceptingHandler (/srv/dist/server.js:104395:23)
    at _callFactory (/srv/dist/server.js:9641:20)
    at _createProviderInstance$1 (/srv/dist/server.js:9595:26)
    at resolveNgModuleDep (/srv/dist/server.js:9558:21)
    at _createClass (/srv/dist/server.js:9620:29)
    at _createProviderInstance$1 (/srv/dist/server.js:9592:26)
    at resolveNgModuleDep (/srv/dist/server.js:9558:21)
    at _createClass (/srv/dist/server.js:9620:29)
    at _createProviderInstance$1 (/srv/dist/server.js:9592:26)
    at resolveNgModuleDep (/srv/dist/server.js:9558:21),
  promise:
   ZoneAwarePromise {
     __zone_symbol__state: 0,
     __zone_symbol__value: TypeError: http.ɵHttpInterceptingHandler is not a constructor
    at zoneWrappedInterceptingHandler (/srv/dist/server.js:104395:23)
    at _callFactory (/srv/dist/server.js:9641:20)
    at _createProviderInstance$1 (/srv/dist/server.js:9595:26)
    at resolveNgModuleDep (/srv/dist/server.js:9558:21)
    at _createClass (/srv/dist/server.js:9620:29)
    at _createProviderInstance$1 (/srv/dist/server.js:9592:26)
    at resolveNgModuleDep (/srv/dist/server.js:9558:21)
    at _createClass (/srv/dist/server.js:9620:29)
    at _createProviderInstance$1 (/srv/dist/server.js:9592:26)
    at resolveNgModuleDep (/srv/dist/server.js:9558:21) },
  zone:
   Zone {
     _properties: { isAngularZone: true },
     _parent:
      Zone {
        _properties: {},
        _parent: null,
        _name: '<root>',
        _zoneDelegate: [Object] },
     _name: 'angular',
     _zoneDelegate:
      ZoneDelegate {
        _taskCounts: [Object],
        zone: [Circular],
        _parentDelegate: [Object],
        _forkZS: null,
        _forkDlgt: null,
        _forkCurrZone: [Object],
        _interceptZS: null,
        _interceptDlgt: null,
        _interceptCurrZone: [Object],
        _invokeZS: [Object],
        _invokeDlgt: [Object],
        _invokeCurrZone: [Circular],
        _handleErrorZS: [Object],
        _handleErrorDlgt: [Object],
        _handleErrorCurrZone: [Circular],
        _scheduleTaskZS: [Object],
        _scheduleTaskDlgt: [Object],
        _scheduleTaskCurrZone: [Circular],
        _invokeTaskZS: [Object],
        _invokeTaskDlgt: [Object],
        _invokeTaskCurrZone: [Circular],
        _cancelTaskZS: [Object],
        _cancelTaskDlgt: [Object],
        _cancelTaskCurrZone: [Circular],
        _hasTaskZS: [Object],
        _hasTaskDlgt: [Object],
        _hasTaskDlgtOwner: [Circular],
        _hasTaskCurrZone: [Circular] } },
  task:
   ZoneTask {
     _zone:
      Zone {
        _properties: [Object],
        _parent: [Object],
        _name: 'angular',
        _zoneDelegate: [Object] },
     runCount: 0,
     _zoneDelegates: null,
     _state: 'notScheduled',
     type: 'microTask',
     source: 'Promise.then',
     data:
      ZoneAwarePromise {
        __zone_symbol__state: 0,
        __zone_symbol__value: TypeError: http.ɵHttpInterceptingHandler is not a constructor
    at zoneWrappedInterceptingHandler (/srv/dist/server.js:104395:23)
    at _callFactory (/srv/dist/server.js:9641:20)
    at _createProviderInstance$1 (/srv/dist/server.js:9595:26)
    at resolveNgModuleDep (/srv/dist/server.js:9558:21)
    at _createClass (/srv/dist/server.js:9620:29)
    at _createProviderInstance$1 (/srv/dist/server.js:9592:26)
    at resolveNgModuleDep (/srv/dist/server.js:9558:21)
    at _createClass (/srv/dist/server.js:9620:29)
    at _createProviderInstance$1 (/srv/dist/server.js:9592:26)
    at resolveNgModuleDep (/srv/dist/server.js:9558:21) },
     scheduleFn: undefined,
     cancelFn: null,
     callback: [Function],
     invoke: [Function] } }

```

## Expected behavior

I would expect to see login page.

## Environment

<pre><code>
Angular version: 6.0.1

Browser:
- [X] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v8.9.4  
- Platform:  Mac 

Others:

</code></pre>

**Comment by chrisleekr** [comment]
For those who experience same issue, please note that the solution is upgrading `@angular/core` to latest.

Based on this comment (https://github.com/angular/universal/issues/1018#issuecomment-396403247), I upgraded all angular packages to 6.0.7 and the error is resolved. Although, I got another issue now. 

Closed the issue.
