### ISSUE TITLE
ReferenceError: MouseEvent is not defined

### ISSUE THREAD

**Issue by MaxSwank** [maciejtreder/ng-toolkit#378]
## I'm submitting a...

<pre><code>
[ X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[X ] @ng-toolkit/universal
</code></pre>

## Current behavior

After quite a bit of work I was able to get a successful build.   However running the server (npm run server) fails with the following errors

> ng build --prod

 69% building modules 652/661 modules 9 active …components\spinner\spinner.ngfactory.jsDEPRECATION WARNING on line 5, column 8 of stdin: il 69% building modules 652/662 modules 10 active …roller\live-app-controller.component.tses with @import is non-standard behaviour which will be removed in future versions of LibSass.             cust 69% building modules 653/662 modules 9 active …components\spinner\socumentation o 69% building modules 653/663 modules 10 active …l3-singer-header.component.ngfactory.jsn how to create a custom importer.
Date: 2018-07-17T05:09:31.847Z
Hash: 89cbf44b79bbfc7f8b55
Time: 55542ms
chunk {scripts} scripts.abc521399cddc9dfff22.js (scripts) 213 kB  [rendered]
chunk {0} runtime.a66f828dca56eeb90e02.js (runtime) 1.05 kB [entry] [rendered]
chunk {1} styles.1c7c749ab96b30966a4d.css (styles) 275 kB [initial] [rendered]
chunk {2} polyfills.23fa5a12ebb4c728ee22.js (polyfills) 98.1 kB [initial] [rendered]
chunk {3} main.6df4b73f3741029cdd53.js (main) 4.39 MB [initial] [rendered]
PS C:\Projects\TestApp\TestApp> npm run server

> TestApp@0.0.0 server C:\Projects\TestApp\TestApp
> node local.js

C:\Projects\TestApp\TestApp\dist\server.js:260546
        __metadata("design:paramtypes", [MouseEvent]),
                                         ^

ReferenceError: MouseEvent is not defined
    at C:\Projects\TestApp\TestApp\dist\server.js:260546:42
    at Object../node_modules/primeng/components/table/table.js (C:\Projects\TestApp\TestApp\dist\server.js:260561:2)
    at __webpack_require__ (C:\Projects\TestApp\TestApp\dist\server.js:245758:30)
    at Object../node_modules/primeng/components/table/table.ngfactory.js (C:\Projects\TestApp\TestApp\dist\server.js:261524:10)
    at __webpack_require__ (C:\Projects\TestApp\TestApp\dist\server.js:245758:30)
    at Object../src/app/home/venue/venueprofile/venueschedule/venueschedule.component.ngfactory.js (C:\Projects\TestApp\TestApp\dist\server.js:280232:11)
    at __webpack_require__ (C:\Projects\TestApp\TestApp\dist\server.js:245758:30)
    at Object../src/app/home/venue/venueprofile/venueprofile.component.ngfactory.js (C:\Projects\TestApp\TestApp\dist\server.js:279965:11)
    at __webpack_require__ (C:\Projects\TestApp\TestApp\dist\server.js:245758:30)
    at Object../src/app/home/content/map-controller/map-overlay/map-overlay.component.ngfactory.js (C:\Projects\TestApp\TestApp\dist\server.js:272958:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1<code>

## Environment

<pre>
Angular version: 6.0.8

Browser:
- [ X] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.11.3 
- Platform:  Windows

Others:

</code></pre>

**Comment by MaxSwank** [comment]
I was led to believe that this request would be addressed in less than a one, maybe two minutes tops...kidding, but no seriously any ideas?
