### ISSUE TITLE
Firebase / AngularFire related error when loading

### ISSUE THREAD

**Issue by alejandroquadri** [maciejtreder/ng-toolkit#380]
## I'm submitting a...

<pre><code>
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[x] @ng-toolkit/universal
</code></pre>

## Current behavior
`npm run server`  
Some firebase related warning show in the console but seems to compile ok. When refreshing at localhost:8080 a blank screen with two curly brackets {} is loaded.

The console shows 

`ERROR TypeError: Cannot read property 'filter' of undefined
    at _firebaseAppFactory (/Users/alejandroquadri/Dev/webs/quadri-web/dist/server.js:53335:174)
    at /Users/alejandroquadri/Dev/webs/quadri-web/dist/server.js:153550:66
    at ZoneDelegate.module.exports.ZoneDelegate.invoke (/Users/alejandroquadri/Dev/webs/quadri-web/dist/server.js:199616:26)
    at Zone.module.exports.Zone.run (/Users/alejandroquadri/Dev/webs/quadri-web/dist/server.js:199366:43)
    at NgZone.module.exports.NgZone.runOutsideAngular (/Users/alejandroquadri/Dev/webs/quadri-web/dist/server.js:4068:28)
    at new AngularFireDatabase (/Users/alejandroquadri/Dev/webs/quadri-web/dist/server.js:153549:30)
    at _createClass (/Users/alejandroquadri/Dev/webs/quadri-web/dist/server.js:8575:20)
    at _createProviderInstance$1 (/Users/alejandroquadri/Dev/webs/quadri-web/dist/server.js:8537:26)
    at resolveNgModuleDep (/Users/alejandroquadri/Dev/webs/quadri-web/dist/server.js:8500:21)
    at _createClass (/Users/alejandroquadri/Dev/webs/quadri-web/dist/server.js:8567:68)
TypeError: Cannot read property 'filter' of undefined
    at _firebaseAppFactory (/Users/alejandroquadri/Dev/webs/quadri-web/dist/server.js:53335:174)
    at /Users/alejandroquadri/Dev/webs/quadri-web/dist/server.js:153550:66
    at ZoneDelegate.module.exports.ZoneDelegate.invoke (/Users/alejandroquadri/Dev/webs/quadri-web/dist/server.js:199616:26)
    at Zone.module.exports.Zone.run (/Users/alejandroquadri/Dev/webs/quadri-web/dist/server.js:199366:43)
    at NgZone.module.exports.NgZone.runOutsideAngular (/Users/alejandroquadri/Dev/webs/quadri-web/dist/server.js:4068:28)
    at new AngularFireDatabase (/Users/alejandroquadri/Dev/webs/quadri-web/dist/server.js:153549:30)
    at _createClass (/Users/alejandroquadri/Dev/webs/quadri-web/dist/server.js:8575:20)
    at _createProviderInstance$1 (/Users/alejandroquadri/Dev/webs/quadri-web/dist/server.js:8537:26)
    at resolveNgModuleDep (/Users/alejandroquadri/Dev/webs/quadri-web/dist/server.js:8500:21)
    at _createClass (/Users/alejandroquadri/Dev/webs/quadri-web/dist/server.js:8567:68)`

app compiles perfectly when running 
`ng serve`

## Minimal reproduction of the problem with instructions
just run `npm run server` and try to load at localhost:8080

## Example repository
https://github.com/alejandroquadri/quadri-web.git
seo-friendly branch

## Environment

Angular CLI: 6.0.8
Node: 8.11.3
OS: darwin x64
Angular: 6.0.7

Browser:
- [x] Chrome (desktop) version 67.0.3396.99 (Build oficial) (64 bits)
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.11.3 
- Platform:  Mac

**Comment by Konondo** [comment]
This is apparently an issue with Angularfire2 (see thread https://github.com/angular/angularfire2/issues/1705).
 The solution of anasbaddyr works for me : 
"
Using rc.11 i went to node_modules/angularfire2/firebase.app.module.js
I changed
import * as firebase from 'firebase/app';
to
import firebase from 'firebase/app';
"

**Comment by alejandroquadri** [comment]
Still getting a lot of warnings in the console, but the app seems to compile correctly. Loads fine too.

**Comment by Rubenazo** [comment]
@Konondo that didn't work for me, using rc.11 changed same line, got same result.

**Comment by philip-firstorder** [comment]
Changed import lines but now I get this:
```
WARNING in ./node_modules/ws/lib/buffer-util.js
Module not found: Error: Can't resolve 'bufferutil' in '/Users/philip_sultanescu/Projects/togaimperial.com/node_modules/ws/lib'
 @ ./node_modules/ws/lib/buffer-util.js
 @ ./node_modules/ws/lib/receiver.js
 @ ./node_modules/ws/index.js
 @ ./server.ts

WARNING in ./node_modules/ws/lib/validation.js
Module not found: Error: Can't resolve 'utf-8-validate' in '/Users/philip_sultanescu/Projects/togaimperial.com/node_modules/ws/lib'
 @ ./node_modules/ws/lib/validation.js
 @ ./node_modules/ws/lib/receiver.js
 @ ./node_modules/ws/index.js
 @ ./server.ts

> togaimperial@0.0.0 generate:prerender /Users/philip_sultanescu/Projects/togaimperial.com
> cd dist && node prerender

/Users/philip_sultanescu/Projects/togaimperial.com/dist/prerender.js:282
                        throw error;
                        ^

ReferenceError: XMLHttpRequest is not defined
    at Qc (/Users/philip_sultanescu/Projects/togaimperial.com/dist/prerender.js:194013:1401)
    at T.g.fa (/Users/philip_sultanescu/Projects/togaimperial.com/dist/prerender.js:194043:234)
    at Xc (/Users/philip_sultanescu/Projects/togaimperial.com/dist/prerender.js:194015:266)
    at Vc (/Users/philip_sultanescu/Projects/togaimperial.com/dist/prerender.js:194014:297)
    at ye.g.Qa (/Users/philip_sultanescu/Projects/togaimperial.com/dist/prerender.js:194057:22)
    at Timeout.<anonymous> (/Users/philip_sultanescu/Projects/togaimperial.com/dist/prerender.js:194013:802)
    at ZoneDelegate.invokeTask (/Users/philip_sultanescu/Projects/togaimperial.com/dist/prerender.js:511:31)
    at Zone.runTask (/Users/philip_sultanescu/Projects/togaimperial.com/dist/prerender.js:278:47)
    at ZoneTask.invokeTask (/Users/philip_sultanescu/Projects/togaimperial.com/dist/prerender.js:586:34)
    at Timeout.ZoneTask.invoke (/Users/philip_sultanescu/Projects/togaimperial.com/dist/prerender.js:575:48)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! togaimperial@0.0.0 generate:prerender: `cd dist && node prerender`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the togaimperial@0.0.0 generate:prerender script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by KingDarBoja** [comment]
Closing now for housekeeping purposes.
