### ISSUE TITLE
ReferenceError: document is not defined

### ISSUE THREAD

**Issue by JonasJW** [maciejtreder/ng-toolkit#409]
## I'm submitting a...

<pre><code>
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[x] @ng-toolkit/universal
</code></pre>

## Current behavior

I do the following steps:

`ng add @ng-toolkit/universal``
'npm run build:prod`
`npm run server``

It gives me my local server url but then I open the link I get this:

`ERROR ReferenceError: document is not defined
    at new AppComponent (/Users/jonas/Web Dev/ngTast/dist/server.js:125492:9)
    at createClass (/Users/jonas/Web Dev/ngTast/dist/server.js:9678:20)
    at createDirectiveInstance (/Users/jonas/Web Dev/ngTast/dist/server.js:9561:20)
    at createViewNodes (/Users/jonas/Web Dev/ngTast/dist/server.js:10781:36)
    at createRootView (/Users/jonas/Web Dev/ngTast/dist/server.js:10695:5)
    at Object.createProdRootView [as createRootView] (/Users/jonas/Web Dev/ngTast/dist/server.js:11207:12)
    at ComponentFactory_.module.exports.ComponentFactory_.create (/Users/jonas/Web Dev/ngTast/dist/server.js:9041:29)
    at ComponentFactoryBoundToModule.module.exports.ComponentFactoryBoundToModule.create (/Users/jonas/Web Dev/ngTast/dist/server.js:3690:29)
    at ApplicationRef.module.exports.ApplicationRef.bootstrap (/Users/jonas/Web Dev/ngTast/dist/server.js:4925:40)
    at /Users/jonas/Web Dev/ngTast/dist/server.js:4733:81
ReferenceError: document is not defined
    at new AppComponent (/Users/jonas/Web Dev/ngTast/dist/server.js:125492:9)
    at createClass (/Users/jonas/Web Dev/ngTast/dist/server.js:9678:20)
    at createDirectiveInstance (/Users/jonas/Web Dev/ngTast/dist/server.js:9561:20)
    at createViewNodes (/Users/jonas/Web Dev/ngTast/dist/server.js:10781:36)
    at createRootView (/Users/jonas/Web Dev/ngTast/dist/server.js:10695:5)
    at Object.createProdRootView [as createRootView] (/Users/jonas/Web Dev/ngTast/dist/server.js:11207:12)
    at ComponentFactory_.module.exports.ComponentFactory_.create (/Users/jonas/Web Dev/ngTast/dist/server.js:9041:29)
    at ComponentFactoryBoundToModule.module.exports.ComponentFactoryBoundToModule.create (/Users/jonas/Web Dev/ngTast/dist/server.js:3690:29)
    at ApplicationRef.module.exports.ApplicationRef.bootstrap (/Users/jonas/Web Dev/ngTast/dist/server.js:4925:40)
    at /Users/jonas/Web Dev/ngTast/dist/server.js:4733:81`

I'm not completly sure If its a problem with ng-toolkit/universal but I have googled a lot and tried a lot of thing but nothing helped yet.

## Expected behavior

build a ready to host application with angular universal so its seo friendly

## Minimal reproduction of the problem with instructions

I hope I have described it above well enough

## What is the motivation / use case for changing the behavior?

So it works? Not sure what is meant here...

## Environment

<pre><code>
Angular version: 6.0.3

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX    v8.11.2
- Platform:   Mac

Others:

</code></pre>

**Comment by maciejtreder** [comment]
Hello,

Do you have your project hosted somewhere? As far as I remember, ng-toolkit should wrap all the `document` occurences in the code to the DocumentService (the problem is lack of document object on the server side).

It would be great if I could reproduce this issue on your codebase! Thanks in advance!

**Comment by JonasJW** [comment]
Hi,

I do not have my project hosted somewhere publicly but If you want I can send it to you via Email or so. Let me know how I can contact you.

Thanks for the help!

**Comment by jcjp** [comment]
Hapenning to me as well here is my details:

```
Angular CLI: 8.2.2
Node: 10.16.0
OS: linux x64
Angular: 8.2.2
```
