### ISSUE TITLE
PWA + SSR (SwPush injeector issue)

### ISSUE THREAD

**Issue by maciejtreder** [maciejtreder/ng-toolkit#423]
## I'm submitting a...

<pre><code>
[ x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[ x ] @ng-toolkit/universal
</code></pre>

## Current behavior
Problem with Server-mock-module for PWA stuff:
ERROR { Error: StaticInjectorError(AppServerModule)[SwPush -> NgswCommChannel]: 
  StaticInjectorError(Platform: core)[SwPush -> NgswCommChannel]: 
    NullInjectorError: No provider for NgswCommChannel!
    at NullInjector.module.exports.NullInjector.get (/Users/mtreder/affinity-front-new/dist/server.js:1386:19)
    at resolveToken (/Users/mtreder/affinity-front-new/dist/server.js:1623:24)
    at tryResolveToken (/Users/mtreder/affinity-front-new/dist/server.js:1568:16)
    at StaticInjector.module.exports.StaticInjector.get (/Users/mtreder/affinity-front-new/dist/server.js:1465:20)
    at resolveToken (/Users/mtreder/affinity-front-new/dist/server.js:1623:24)
    at tryResolveToken (/Users/mtreder/affinity-front-new/dist/server.js:1568:16)
    at StaticInjector.module.exports.StaticInjector.get (/Users/mtreder/affinity-front-new/dist/server.js:1465:20)
    at resolveNgModuleDep (/Users/mtreder/affinity-front-new/dist/server.js:8513:29)
    at _createClass (/Users/mtreder/affinity-front-new/dist/server.js:8558:29)
    at _createProviderInstance (/Users/mtreder/affinity-front-new/dist/server.js:8530:26)
  ngTempTokenPath: null,
  ngTokenPath: [ 'SwPush', [Function: NgswCommChannel] ] }

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by sredorta** [comment]
I added this on the app.server.module.ts to solve this issue:
    ServiceWorkerModule.register('ngsw-worker.js', { enabled: **false** }),

**Comment by KingDarBoja** [comment]
Closing now as recent version of `Angular/PWA` schematic already handles this.
