### ISSUE TITLE
@ng-toolkit/universal error on tour of heros

### ISSUE THREAD

**Issue by dayain** [maciejtreder/ng-toolkit#430]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[ ] @ng-toolkit/universal
[ ] @ng-toolkit/pwa
[ ] @ng-toolkit/firebug
</code></pre>

## Environment

<pre><code>
Angular version: X.Y.Z

- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by dayain** [comment]
ng build --prod worked fine but npm run server thew below error


> my-app@0.0.0 server G:\Projects\angular\universal\my-app
> node local.js

module.js:549
    throw err;
    ^

Error: Cannot find module './dist/server'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (G:\Projects\angular\universal\my-app\local.js:4:20)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-app@0.0.0 server: `node local.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the my-app@0.0.0 server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Daya\AppData\Roaming\npm-cache\_logs\2018-09-01T07_53_55_877Z-debug.log

**Comment by KingDarBoja** [comment]
⚠️ Closed as invalid issue. Please, fill the issue template when opening new issues in order to help us track the bug.

Cheers!
