### ISSUE TITLE
Package install failed : ng add @ng-toolkit/serverless --provider aws

### ISSUE THREAD

**Issue by dave-k** [maciejtreder/ng-toolkit#448]
## I'm submitting a...

<pre><code>
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[x] @ng-toolkit/serverless
[ ] @ng-toolkit/universal
[ ] @ng-toolkit/pwa
[ ] @ng-toolkit/firebug
</code></pre>

## Current behavior

    $ ng add @ng-toolkit/serverless --provider aws
    Installing packages for tooling via yarn.
    yarn add v1.9.4
    warning package.json: "dependencies" has dependency "webpack-cli" with range "^2.1.4" that collides with a dependency in "devDependencies" of the same name with version "2.1.2"
    warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
    warning myawesomeapp@0.0.0: "dependencies" has dependency "webpack-cli" with range "^2.1.4" that collides with a dependency in "devDependencies" of the same name with version "2.1.2"
    [1/4] 🔍  Resolving packages...
    [2/4] 🚚  Fetching packages...
    warning Pattern ["@ng-toolkit/serverless@^1.1.41"] is trying to unpack in the same destination "/Users/dev/Library/Caches/Yarn/v2/npm-@ng-toolkit/serverless-1.1.41-56106eead81059071a573a4e2bec56516bd28968" as pattern ["@ng-toolkit/serverless@^1.1.40"]. This could result in non-deterministic behavior, skipping.
    [--------------------------------------------------------------------------------------------------------------------] 0/1419(node:11543) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
    [3/4] 🔗  Linking dependencies...
    warning "@ng-toolkit/universal > @ng-toolkit/pwa@1.1.41" has unmet peer dependency "@angular/service-worker@^6.0.5".
    warning " > @nguniversal/express-engine@6.1.0" has unmet peer dependency "express@^4.15.2".
    warning " > webpack-cli@2.1.5" has unmet peer dependency "webpack@^4.0.0".
    [4/4] 📃  Building fresh packages...
    success Saved 1 new dependency.
    info Direct dependencies
    └─ @ng-toolkit/serverless@1.1.41
    info All dependencies
    └─ @ng-toolkit/serverless@1.1.41
    warning myawesomeapp@0.0.0: "dependencies" has dependency "webpack-cli" with range "^2.1.4" that collides with a dependency in "devDependencies" of the same name with version "2.1.2"
    ✨  Done in 56.08s.
    Installed packages for tooling via yarn.
    INFO: Project property is set to 'myawesomeapp'.
    DELETE serverless.yml
    CREATE serverless.yml (697 bytes)
    UPDATE package.json (2605 bytes)
    UPDATE lambda.js (859 bytes)
    UPDATE local.js (176 bytes)
    UPDATE webpack.server.config.js (1214 bytes)
    UPDATE src/environments/environment.serverless.ts (110 bytes)
    UPDATE src/environments/environment.prod.ts (99 bytes)
    UPDATE src/environments/environment.ts (679 bytes)
    UPDATE angular.json (4166 bytes)
    UPDATE src/app/app.component.ts (1232 bytes)
    UPDATE ng-toolkit.json (289 bytes)
    warning package.json: "dependencies" has dependency "webpack-cli" with range "^2.1.4" that collides with a dependency in "devDependencies" of the same name with version "2.1.2"
    warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
    warning myawesomeapp@0.0.0: "dependencies" has dependency "webpack-cli" with range "^2.1.4" that collides with a dependency in "devDependencies" of the same name with version "2.1.2"
    [--------------------------------------------------------------------------------------------------------------------] 0/1433(node:11607) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
    warning "@ng-toolkit/universal > @ng-toolkit/pwa@1.1.41" has unmet peer dependency "@angular/service-worker@^6.0.5".
    warning " > @nguniversal/express-engine@6.1.0" has unmet peer dependency "express@^4.15.2".
    warning " > webpack-cli@2.1.5" has unmet peer dependency "webpack@^4.0.0".
    error /Users/dev/project3/myawesomeapp/node_modules/serverless: Command failed.
    Exit code: 1
    Command: node ./scripts/postinstall.js
    Arguments: 
    Directory: /Users/dev/project3/myawesomeapp/node_modules/serverless
    Output:
    events.js:167
          throw er; // Unhandled 'error' event
          ^

    Error: socket hang up
        at createHangUpError (_http_client.js:313:15)
        at TLSSocket.socketOnEnd (_http_client.js:416:23)
        at TLSSocket.emit (events.js:187:15)
        at TLSSocket.EventEmitter.emit (domain.js:442:20)
        at endReadableNT (_stream_readable.js:1081:12)
        at process._tickCallback (internal/process/next_tick.js:63:19)
    Emitted 'error' event at:
        at TLSSocket.socketOnEnd (_http_client.js:416:9)
        at TLSSocket.emit (events.js:187:15)
        [... lines matching original stack trace ...]
        at process._tickCallback (internal/process/next_tick.js:63:19)
    Package install failed, see above.

## Minimal reproduction of the problem with instructions

    npm install -g serverless 
    serverless --version
      1.31.0
    serverless config credentials --provider aws --key <>  --secret <>
    ng new myawesomeapp  
    ng add @ng-toolkit/universal
    ng add @ng-toolkit/serverless --provider aws

## Environment

<pre><code>
- Angular version: 

    Angular CLI: 6.1.5
    Node: 10.8.0
    OS: darwin x64
    Angular: 6.1.7
    ... animations, common, compiler, compiler-cli, core, forms
    ... http, language-service, platform-browser
    ... platform-browser-dynamic, platform-server, router

    Package                           Version
    -----------------------------------------------------------
    @angular-devkit/architect         0.7.5
    @angular-devkit/build-angular     0.7.5
    @angular-devkit/build-optimizer   0.7.5
    @angular-devkit/build-webpack     0.7.5
    @angular-devkit/core              0.7.5
    @angular-devkit/schematics        0.7.5
    @angular/cli                      6.1.5
    @ngtools/webpack                  6.1.5
    @schematics/angular               0.7.5
    @schematics/update                0.7.5
    rxjs                              6.3.2
    typescript                        2.7.2
    webpack                           4.9.2

- Node version: 10.8.0  
- Platform:  macOS 10.13.6
- serverless v1.31.0

Others:

</code></pre>

package.json

    {
      "name": "myawesomeapp",
      "version": "0.0.0",
      "scripts": {
        "ng": "ng",
        "start": "ng serve",
        "build": "ng build",
        "test": "ng test",
        "lint": "ng lint",
        "e2e": "ng e2e",
        "build:server:prod": "ng run myawesomeapp:server && webpack --config webpack.server.config.js --progress --colors",
        "build:browser:prod": "ng build --prod",
        "build:prod": "npm run build:browser:prod && npm run build:server:prod",
        "server": "node local.js",
        "build:browser:serverless": "ng build --prod --base-href /production/",
        "build:serverless": "npm run build:browser:serverless && npm run build:server:serverless",
        "build:prod:deploy": "npm run build:prod && npm run deploy",
        "build:serverless:deploy": "npm run build:serverless && npm run deploy",
        "deploy": "serverless deploy",
        "build:server:serverless": "ng run myawesomeapp:server:serverless && webpack --config webpack.server.config.js --progress --colors"
      },
      "private": true,
      "dependencies": {
        "@angular/animations": "^6.1.0",
        "@angular/common": "^6.1.0",
        "@angular/compiler": "^6.1.0",
        "@angular/core": "^6.1.0",
        "@angular/forms": "^6.1.0",
        "@angular/http": "^6.1.0",
        "@angular/platform-browser": "^6.0.0",
        "@angular/platform-browser-dynamic": "^6.1.0",
        "@angular/platform-server": "^6.0.0",
        "@angular/router": "^6.1.0",
        "@ng-toolkit/serverless": "^1.1.41",
        "@ng-toolkit/universal": "^1.1.41-beta.110",
        "@nguniversal/express-engine": "^6.0.0",
        "@nguniversal/module-map-ngfactory-loader": "^6.0.0",
        "aws-serverless-express": "^3.2.0",
        "core-js": "^2.5.4",
        "cors": "~2.8.4",
        "cp-cli": "^1.1.0",
        "rxjs": "^6.0.0",
        "ts-loader": "4.2.0",
        "webpack-cli": "^2.1.4",
        "zone.js": "~0.8.26"
      },
      "devDependencies": {
        "@angular-devkit/build-angular": "~0.7.0",
        "@angular/cli": "~6.1.2",
        "@angular/compiler-cli": "^6.1.0",
        "@angular/language-service": "^6.1.0",
        "@types/jasmine": "~2.8.6",
        "@types/jasminewd2": "~2.0.3",
        "@types/node": "~8.9.4",
        "codelyzer": "~4.2.1",
        "jasmine-core": "~2.99.1",
        "jasmine-spec-reporter": "~4.2.1",
        "karma": "~1.7.1",
        "karma-chrome-launcher": "~2.2.0",
        "karma-coverage-istanbul-reporter": "~2.0.0",
        "karma-jasmine": "~1.1.1",
        "karma-jasmine-html-reporter": "^0.2.2",
        "opencollective": "^1.0.3",
        "protractor": "~5.3.0",
        "serverless": "1.26.1",
        "serverless-apigw-binary": "^0.4.4",
        "ts-loader": "4.2.0",
        "ts-node": "~5.0.1",
        "tslint": "~5.9.1",
        "typescript": "~2.7.2",
        "webpack-cli": "2.1.2"
      }
    }

**Comment by JunjiUmeno** [comment]
This was reproduced again at node 10.14.2. What the heck is this from?

**Comment by Unny** [comment]
I am still getting the same error while using Node version 10.15.3, serverless ver 1.38.0, but in package.json file the version is shown as 1.26.1. Please help to solve the issue
