### ISSUE TITLE
ReferenceError: document is not defined

### ISSUE THREAD

**Issue by freehuoshan** [maciejtreder/ng-toolkit#465]
> node local.js

Listening on: http://localhost:4201
document is not defined
ReferenceError: document is not defined
    at new CssKeyframesDriver (/home/free/gitRespo/website/website-website/dist/server.js:65406:22)
    at instantiateSupportedAnimationDriver (/home/free/gitRespo/website/website-website/dist/server.js:94098:196)
    at _callFactory (/home/free/gitRespo/website/website-website/dist/server.js:9013:20)
    at _createProviderInstance (/home/free/gitRespo/website/website-website/dist/server.js:8971:26)
    at resolveNgModuleDep (/home/free/gitRespo/website/website-website/dist/server.js:8931:21)
    at _createClass (/home/free/gitRespo/website/website-website/dist/server.js:9000:68)
    at _createProviderInstance (/home/free/gitRespo/website/website-website/dist/server.js:8968:26)
    at resolveNgModuleDep (/home/free/gitRespo/website/website-website/dist/server.js:8931:21)
    at _callFactory (/home/free/gitRespo/website/website-website/dist/server.js:9019:67)
    at _createProviderInstance (/home/free/gitRespo/website/website-website/dist/server.js:8971:26)

![image](https://user-images.githubusercontent.com/12974376/46569351-13376c00-c986-11e8-9c61-b93c06912e3b.png)

**Comment by krhomme** [comment]
I also encountered this problem, how do you solve it?

**Comment by KingDarBoja** [comment]
Closing now for housekeeping purposes. Please try the latest releases and open a new issue if the same error occurs.

Cheers!
