### ISSUE TITLE
Error while deploying to AWS

### ISSUE THREAD

**Issue by sdemisse** [maciejtreder/ng-toolkit#470]
## I'm submitting a...

<pre><code>
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[x] @ng-toolkit/serverless
[ ] @ng-toolkit/universal
[ ] @ng-toolkit/pwa
[ ] @ng-toolkit/firebug
</code></pre>

I am getting this error while runing `npm run build:serverless:deploy`
```
TypeError: Cannot read property 'properties' of undefined
    at module.exports (/Users/xxx/workspace/test-lambda/node_modules/webpack-cli/bin/config-yargs.js:89:48)
    at /Users/xxx/workspace/test-lambda/node_modules/webpack-cli/bin/webpack.js:60:27
    at Object.<anonymous> (/Users/xxx/workspace/test-lambda/node_modules/webpack-cli/bin/webpack.js:515:3)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! test-lambda@0.0.0 build:server:serverless: `ng run test-lambda:server:serverless && webpack --config webpack.server.config.js --progress --colors`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the test-lambda@0.0.0 build:server:serverless script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xxx/.npm/_logs/2018-10-08T04_39_12_384Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! test-lambda@0.0.0 build:serverless: `npm run build:browser:serverless && npm run build:server:serverless`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the test-lambda@0.0.0 build:serverless script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xxx/.npm/_logs/2018-10-08T04_39_12_402Z-debug.log
```

**Comment by ferhado** [comment]
I have the same issue. Have you solved it?

**Comment by mukulvtilak** [comment]
Same issue, any resolution/cause of this?
