### ISSUE TITLE
when i run the command npm run build:prod getting error ( TypeError: Cannot read property 'properties' of undefined )

### ISSUE THREAD

**Issue by venukumarvk** [maciejtreder/ng-toolkit#480]
Im using 
Angular CLI: 6.2.4
Node: 8.9.4
When i run the command npm run build:prod getting error as

> awesome-seo@0.0.0 build:prod /var/www/html/awesome-seo
> npm run build:server:prod && npm run build:browser:prod

> awesome-seo@0.0.0 build:server:prod /var/www/html/awesome-seo
> ng run awesome-seo:server && webpack --config webpack.server.config.js --progress --colors

                                                                                       
Date: 2018-10-16T05:43:30.263Z
Hash: 3090d38c6a8de8667767
Time: 9040ms
chunk {main} main.js, main.js.map (main) 33 kB [entry] [rendered]
/var/www/html/awesome-seo/node_modules/webpack-cli/bin/config-yargs.js:89
				describe: optionsSchema.definitions.output.properties.path.description,
				                                           ^

TypeError: Cannot read property 'properties' of undefined
    at module.exports (/var/www/html/awesome-seo/node_modules/webpack-cli/bin/config-yargs.js:89:48)
    at /var/www/html/awesome-seo/node_modules/webpack-cli/bin/webpack.js:60:27
    at Object.<anonymous> (/var/www/html/awesome-seo/node_modules/webpack-cli/bin/webpack.js:515:3)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! awesome-seo@0.0.0 build:server:prod: `ng run awesome-seo:server && webpack --config webpack.server.config.js --progress --colors`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the awesome-seo@0.0.0 build:server:prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/rajni/.npm/_logs/2018-10-16T05_43_30_433Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! awesome-seo@0.0.0 build:prod: `npm run build:server:prod && npm run build:browser:prod`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the awesome-seo@0.0.0 build:prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/rajni/.npm/_logs/2018-10-16T05_43_30_452Z-debug.log

Please can any one help me to figure out this issue.
Thanks in advance.

This is my package.json file content

{
  "name": "awesome-seo",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "build:server:prod": "ng run awesome-seo:server && webpack --config webpack.server.config.js --progress --colors",
    "build:browser:prod": "ng build --prod",
    "build:prod": "npm run build:server:prod && npm run build:browser:prod",
    "server": "node local.js"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^6.1.0",
    "@angular/common": "^6.1.0",
    "@angular/compiler": "^6.1.0",
    "@angular/core": "^6.1.0",
    "@angular/forms": "^6.1.0",
    "@angular/http": "^6.1.0",
    "@angular/platform-browser": "^6.0.0",
    "@angular/platform-browser-dynamic": "^6.1.0",
    "@angular/router": "^6.1.0",
    "@ng-toolkit/universal": "^1.1.41-beta.110",
    "core-js": "^2.5.4",
    "rxjs": "~6.2.0",
    "zone.js": "~0.8.26",
    "@angular/platform-server": "^6.0.0",
    "@nguniversal/module-map-ngfactory-loader": "^6.0.0",
    "webpack-cli": "^2.1.4",
    "ts-loader": "4.2.0",
    "@nguniversal/express-engine": "^6.0.0",
    "cors": "~2.8.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.8.0",
    "@angular/cli": "~6.2.4",
    "@angular/compiler-cli": "^6.1.0",
    "@angular/language-service": "^6.1.0",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.3.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~3.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~2.9.2"
  }
}

**Comment by Simon-Bru** [comment]
I fixed it by upgrading webpack-cli. Just run:
`npm install webpack-cli@latest`

And it should work :)

**Comment by venukumarvk** [comment]
Thanks it worked for me.

**Comment by Simon-Bru** [comment]
You should close the issue
