### ISSUE TITLE
Error while run 'npm run build:prod' with @ng-toolkit/universal project

### ISSUE THREAD

**Issue by DineshChopra** [maciejtreder/ng-toolkit#483]
## I'm submitting a...

<pre><code>
 Bug report  
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/universal
</code></pre>

## Current behavior

When I try to generate a build via `npm run build:prod`, It gives me an error. Error logs are given below:

describe: optionsSchema.definitions.output.properties.path.description,
TypeError: Cannot read property 'properties' of undefined
    at module.exports (E:\RND\homlun\node_modules\webpack-cli\bin\config-yargs.js:89:48)
    at E:\RND\homlun\node_modules\webpack-cli\bin\webpack.js:60:27
    at Object.<anonymous> (E:\RND\homlun\node_modules\webpack-cli\bin\webpack.js:515:3)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)

## Expected behavior
It should generate a build for angular app

## Minimal reproduction of the problem with instructions
Create a new project with angular-cli `ng new test-app`
Add universal functionality -- `ng add @ng-toolkit/universal`
Run build command -- `ng run build:server`

## What is the motivation / use case for changing the behavior?
If that problem is resolved, it makes my life easier. In just two steps I am ready to build an SEO  friendly app. Which is the purpose of @ng-toolkit/universal

## Environment

<pre><code>
Angular version: 6.1.0

- Node version: v8.12.0
- Platform: Windows  

Others:

</code></pre>

**Comment by krishollenbeck** [comment]
I was also seeing this issue. Looks like the version of webpack-cli `^2.1..4` is pulling in a broken webpack.js file. Looking at the code it appears as if a comment was somehow stripped and is no longer in comment format.

Upgradding to `"webpack-cli": "^3.1.2"` fixed the issue for me.
