### ISSUE TITLE
Bug when trying to access localhost:8080 after npm run server

### ISSUE THREAD

**Issue by GZM047** [maciejtreder/ng-toolkit#491]
## I'm submitting a...

<pre><code>
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[x] @ng-toolkit/universal
[ ] @ng-toolkit/pwa
[ ] @ng-toolkit/firebug
</code></pre>

## Current behavior

ng serve - works
npm run build:prod - works
npm run server - works
accessing website on localhost:8080 - doesn't work

## Expected behavior

ng serve - works
npm run build:prod - works
npm run server - works
accessing website on localhost:8080 should work if all the above have built successfully

## Minimal reproduction of the problem with instructions

ng serve
npm run build:prod
npm run server
access website on localhost:8080

## Environment

<pre><code>
Angular version: 7.0.1
Angular CLI version: 7.0.3

- Node version: 8.9.4  
- Platform:  Win32 x64

![capture](https://user-images.githubusercontent.com/44571907/47646231-89895180-db73-11e8-973c-7231211018d6.JPG)

**Comment by Jucuzzi** [comment]
I meet the same problem ! how to resolve this?

**Comment by kunalairasia** [comment]
@maciejtreder Got a similar issue during ```build:prerender```. Seems like issue with ```document.cookie``` ? Kinda stuck here.

```
ERROR Error: NotYetImplemented
    at Document.module.exports.exports.nyi (/Users/kunalmz/Desktop/Repos/content-publisher-new/content-publisher/dist/prerender.js:94715:9)
    at UserdataService.module.exports.UserdataService.getCookie (/Users/kunalmz/Desktop/Repos/content-publisher-new/content-publisher/dist/prerender.js:159286:27)
    at new UserdataService (/Users/kunalmz/Desktop/Repos/content-publisher-new/content-publisher/dist/prerender.js:159067:94)
```

Here ```getCookie``` method is trying to perform some cookie based operation.
