### ISSUE TITLE
Error: spawn C:\WINDOWS\system32\cmd.exe ENOENT

### ISSUE THREAD

**Issue by gauravkfoujdar** [maciejtreder/ng-toolkit#503]
## I'm submitting a...

<pre><code>
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ x] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[ ] @ng-toolkit/universal
[ ] @ng-toolkit/pwa
[ ] @ng-toolkit/firebug
</code></pre>

## Current behavior

Creating a new project in a drive other than C drive of my desktop generates the mentioned stack trace.

```
ng new --collection @ng-toolkit/init myApp
INFO: Project property is set to 'myApp'.
CREATE myApp/angular.json (4853 bytes)
CREATE myApp/package.json (3614 bytes)
CREATE myApp/README.md (5136 bytes)
CREATE myApp/tsconfig.json (521 bytes)
CREATE myApp/tslint.json (1510 bytes)
CREATE myApp/.editorconfig (245 bytes)
CREATE myApp/.gitignore (174 bytes)
CREATE myApp/src/favicon.ico (5430 bytes)
CREATE myApp/src/index.html (5465 bytes)
CREATE myApp/src/polyfills.ts (3107 bytes)
CREATE myApp/src/test.ts (664 bytes)
CREATE myApp/src/styles.css (80 bytes)
CREATE myApp/src/browserslist (388 bytes)
CREATE myApp/src/karma.conf.js (964 bytes)
CREATE myApp/src/tsconfig.app.json (306 bytes)
CREATE myApp/src/tsconfig.spec.json (283 bytes)
CREATE myApp/src/tslint.json (314 bytes)
CREATE myApp/src/assets/.gitkeep (0 bytes)
CREATE myApp/src/environments/environment.prod.ts (67 bytes)
CREATE myApp/src/environments/environment.ts (678 bytes)
CREATE myApp/src/app/app.module.ts (3268 bytes)
CREATE myApp/src/app/app.component.html (461 bytes)
CREATE myApp/src/app/app.component.spec.ts (4784 bytes)
CREATE myApp/src/app/app.component.ts (3075 bytes)
CREATE myApp/src/app/app.component.css (0 bytes)
CREATE myApp/e2e/protractor.conf.js (752 bytes)
CREATE myApp/e2e/tsconfig.e2e.json (213 bytes)
CREATE myApp/e2e/src/app.e2e-spec.ts (301 bytes)
CREATE myApp/e2e/src/app.po.ts (208 bytes)
CREATE myApp/credentials.js (368 bytes)
CREATE myApp/LICENSE (1070 bytes)
CREATE myApp/local.js (176 bytes)
CREATE myApp/ngsw-config.json (783 bytes)
CREATE myApp/src/main.server.ts (218 bytes)
CREATE myApp/src/manifest.json (1203 bytes)
CREATE myApp/src/tsconfig.server.json (399 bytes)
CREATE myApp/src/app/app.browser.module.ts (1172 bytes)
CREATE myApp/src/app/app.component.scss (521 bytes)
CREATE myApp/src/app/app.server.module.ts (1501 bytes)
CREATE myApp/src/app/window-ref.service.ts (764 bytes)
CREATE myApp/src/app/donors/donors.component.html (1790 bytes)
CREATE myApp/src/app/donors/donors.component.ts (286 bytes)
CREATE myApp/src/app/home/home.component.html (2715 bytes)
CREATE myApp/src/app/home/home.component.spec.ts (625 bytes)
CREATE myApp/src/app/home/home.component.ts (211 bytes)
CREATE myApp/src/app/lazy/lazy.component.html (405 bytes)
CREATE myApp/src/app/lazy/lazy.component.spec.ts (641 bytes)
CREATE myApp/src/app/lazy/lazy.component.ts (158 bytes)
CREATE myApp/src/app/lazy/lazy.module.ts (331 bytes)
CREATE myApp/src/app/menu/menu.component.html (1740 bytes)
CREATE myApp/src/app/menu/menu.component.scss (1069 bytes)
CREATE myApp/src/app/menu/menu.component.spec.ts (4588 bytes)
CREATE myApp/src/app/menu/menu.component.ts (2165 bytes)
CREATE myApp/src/app/services/exampleApi.service.ts (426 bytes)
CREATE myApp/src/app/services/notifications.service.spec.ts (7765 bytes)
CREATE myApp/src/app/services/notifications.service.ts (4730 bytes)
CREATE myApp/src/app/services/service-worker.mock.module.ts (430 bytes)
CREATE myApp/src/app/services/snack-bar.service.spec.ts (4001 bytes)
CREATE myApp/src/app/services/snack-bar.service.ts (2296 bytes)
CREATE myApp/src/app/services/swPush-server.mock.service.ts (442 bytes)
CREATE myApp/src/app/services/swUpdate-server.mock.service.ts (549 bytes)
CREATE myApp/src/app/services/resolvers/hitWithoutTransferState.resolver.ts (485 bytes)
CREATE myApp/src/app/services/resolvers/hitWithTransferState.resolver.ts (1251 bytes)
CREATE myApp/src/app/transfer-state/transfer-state.component.css (1115 bytes)
CREATE myApp/src/app/transfer-state/transfer-state.component.html (2549 bytes)
CREATE myApp/src/app/transfer-state/transfer-state.component.ts (376 bytes)
CREATE myApp/src/app/transfer-state/with-transfer-state.component.ts (552 bytes)
CREATE myApp/src/app/transfer-state/without-transfer-state.component.ts (555 bytes)
CREATE myApp/src/assets/browserconfig.xml (259 bytes)
CREATE myApp/src/assets/i18n/de.json (35 bytes)
CREATE myApp/src/assets/i18n/en.json (32 bytes)
CREATE myApp/src/assets/i18n/es.json (34 bytes)
CREATE myApp/src/assets/i18n/fr.json (34 bytes)
CREATE myApp/src/assets/i18n/hi.json (60 bytes)
CREATE myApp/src/assets/i18n/it.json (33 bytes)
CREATE myApp/src/assets/i18n/nl.json (32 bytes)
CREATE myApp/src/assets/i18n/pl.json (27 bytes)
CREATE myApp/src/assets/i18n/ru.json (56 bytes)
CREATE myApp/src/assets/i18n/sk.json (31 bytes)
CREATE myApp/src/assets/i18n/tr.json (34 bytes)
CREATE myApp/src/assets/icons/favicon-144.png (4335 bytes)
CREATE myApp/src/assets/icons/favicon-192.png (6502 bytes)
CREATE myApp/src/assets/icons/favicon-32.png (573 bytes)
CREATE myApp/src/assets/icons/favicon-48.png (950 bytes)
CREATE myApp/src/assets/icons/favicon-512.png (28650 bytes)
CREATE myApp/src/assets/icons/favicon-72.png (1684 bytes)
CREATE myApp/src/assets/icons/favicon-96.png (2544 bytes)
CREATE myApp/src/assets/icons/favicon.ico (152126 bytes)
CREATE myApp/src/assets/icons/favicon.png (6502 bytes)
CREATE myApp/src/assets/icons/mstile-150x150.png (4692 bytes)
CREATE myApp/src/assets/icons/safari-pinned-tab.svg (35212 bytes)
CREATE myApp/src/assets/img/background.png (72398 bytes)
CREATE myApp/src/assets/img/lighthouse_report.png (28918 bytes)
CREATE myApp/src/styles/credentials.scss (405 bytes)
CREATE myApp/src/styles/main.scss (779 bytes)
CREATE myApp/src/main.browser.ts (392 bytes)
CREATE myApp/ng-toolkit.json (185 bytes)
CREATE myApp/webpack.server.config.js (1091 bytes)
CREATE myApp/server.ts (1228 bytes)
CREATE myApp/temp/server_static.ts9 (539 bytes)
CREATE myApp/lambda.js (859 bytes)
CREATE myApp/serverless.yml (690 bytes)
CREATE myApp/src/environments/environment.serverless.ts (78 bytes)
Bugsnag:  Encountered an uncaught error, terminating…
Error: spawn C:\WINDOWS\system32\cmd.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:11)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
```

## Expected behavior

The project should be created successfully.

## Minimal reproduction of the problem with instructions

Create a project in a drive other than C drive in windows 10.

## Environment

<pre><code>
Angular CLI: 7.0.5
Node: 10.13.0
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.10.5
@angular-devkit/core         7.0.5
@angular-devkit/schematics   7.0.5
@schematics/angular          7.0.5
@schematics/update           0.10.5
rxjs                         6.3.3
typescript                   3.1.6

**Comment by stijnwesterhof** [comment]
Any fix?

**Comment by KingDarBoja** [comment]
Closed for housekeeping purposes.
