### ISSUE TITLE
the server responded with a status of 404

### ISSUE THREAD

**Issue by parth2495** [maciejtreder/ng-toolkit#582]
Hello,
I have created a Project in angular 7 and I have also hosted it on Heroku by creating express server and server.js file to serve index.html 
Everything was working fine but when I wanted to add Angular Universal, I have added ng-toolkit/Universal to my Project now It is not able to serve any content at all. Can you please help me out.

ng-toolkit/Universal has added following files to my Project.
create mode 100644 local.js
 create mode 100644 ng-toolkit.json
 create mode 100644 server.ts
 create mode 100644 src/app/app.browser.module.ts
 create mode 100644 src/app/app.server.module.ts
 create mode 100644 src/main.server.ts
 create mode 100644 src/tsconfig.server.json
 create mode 100644 webpack.server.config.js

**Comment by parth2495** [comment]
This is an error I am getting 
(function (exports, require, module, __filename, __dirname) { import 'zone.js/dist/zone-node';
2019-03-27T15:58:43.784439+00:00 app[web.1]: ^^^^^^
2019-03-27T15:58:43.784440+00:00 app[web.1]:
2019-03-27T15:58:43.784442+00:00 app[web.1]: SyntaxError: Unexpected token import
2019-03-27T15:58:43.784444+00:00 app[web.1]: at createScript (vm.js:80:10)
2019-03-27T15:58:43.784445+00:00 app[web.1]: at Object.runInThisContext (vm.js:139:10)
2019-03-27T15:58:43.784447+00:00 app[web.1]: at Module._compile (module.js:599:28)
2019-03-27T15:58:43.784449+00:00 app[web.1]: at Object.Module._extensions..js (module.js:646:10)
2019-03-27T15:58:43.784450+00:00 app[web.1]: at Module.load (module.js:554:32)
2019-03-27T15:58:43.784452+00:00 app[web.1]: at tryModuleLoad (module.js:497:12)
2019-03-27T15:58:43.784454+00:00 app[web.1]: at Function.Module._load (module.js:489:3)
2019-03-27T15:58:43.784455+00:00 app[web.1]: at Function.Module.runMain (module.js:676:10)
2019-03-27T15:58:43.784457+00:00 app[web.1]: at startup (bootstrap_node.js:187:16)
2019-03-27T15:58:43.784458+00:00 app[web.1]: at bootstrap_node.js:608:3
2019-03-27T15:58:43.797330+00:00 app[web.1]: npm ERR! code ELIFECYCLE
