### ISSUE TITLE
ERROR TypeError: Cannot read property 'pipe' of undefined

### ISSUE THREAD

**Issue by bellib** [maciejtreder/ng-toolkit#583]
Hi , 
When i  run this 
`npm run server`
I have this error 
```
 npm run server

> hesee@0.0.1 server E:\hesee
> node local.js

Listening on: http://localhost:8080
ERROR TypeError: Cannot read property 'pipe' of undefined
    at TransferHttpCacheInterceptor.module.exports.TransferHttpCacheInterceptor.intercept (E:\hesee\dist\server.js:134530:18)
    at HttpInterceptorHandler.module.exports.HttpInterceptorHandler.handle (E:\hesee\dist\server.js:68648:33)
    at HttpInterceptingHandler.module.exports.HttpInterceptingHandler.handle (E:\hesee\dist\server.js:69283:27)
    at ZoneClientBackend.module.exports.ZoneClientBackend.delegate (E:\hesee\dist\server.js:78174:29)
    at scheduleTask (E:\hesee\dist\server.js:78079:38)
    at Observable._subscribe (E:\hesee\dist\server.js:78118:13)
    at Observable.module.exports.Observable._trySubscribe (E:\hesee\dist\server.js:53646:25)
    at Observable.module.exports.Observable.subscribe (E:\hesee\dist\server.js:53632:22)
    at E:\hesee\dist\server.js:80504:31
    at subscribeToResult (E:\hesee\dist\server.js:67369:92)
ERROR TypeError: Cannot read property 'pipe' of undefined
    at TransferHttpCacheInterceptor.module.exports.TransferHttpCacheInterceptor.intercept (E:\hesee\dist\server.js:134530:18)
    at HttpInterceptorHandler.module.exports.HttpInterceptorHandler.handle (E:\hesee\dist\server.js:68648:33)
    at HttpInterceptingHandler.module.exports.HttpInterceptingHandler.handle (E:\hesee\dist\server.js:69283:27)
    at ZoneClientBackend.module.exports.ZoneClientBackend.delegate (E:\hesee\dist\server.js:78174:29)
    at scheduleTask (E:\hesee\dist\server.js:78079:38)
    at Observable._subscribe (E:\hesee\dist\server.js:78118:13)
    at Observable.module.exports.Observable._trySubscribe (E:\hesee\dist\server.js:53646:25)
    at Observable.module.exports.Observable.subscribe (E:\hesee\dist\server.js:53632:22)
    at E:\hesee\dist\server.js:80504:31
    at subscribeToResult (E:\hesee\dist\server.js:67369:92)
```

And the line  134530 is 
![2019-03-27_21-10-33](https://user-images.githubusercontent.com/3954893/55109071-3c36ef00-50d5-11e9-8e07-77c6eb2b63fa.jpg)

**Comment by KingDarBoja** [comment]
⚠️ Closed as invalid issue. Please, fill the issue template when opening new issues in order to help us track the bug.

Cheers!
