### ISSUE TITLE
prerender.js says undefined component: <Components in routing.module.ts>

### ISSUE THREAD

**Issue by ank1106** [maciejtreder/ng-toolkit#613]
## I'm submitting a...

<pre><code>
[] Bug report  
[ ] Feature request
[x] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[x] @ng-toolkit/universal
[ ] @ng-toolkit/pwa
[ ] @ng-toolkit/firebug
</code></pre>

## Current behavior

when I run npm run build:prerender then without app.routing.module it works fine but with having  routing.module file gives an error of undefined component. 

## Minimal reproduction of the problem with instructions

create a new angular app
1.) ng new some-app
2.) choose yes for routing
3) run ng add @ng-toolkit/universal
4) then do npm run build:prerender

it will work fine
now 
5) create a component let say 'SomeComponent' and add it to app-routing.module
6) run step 4.)
it will give below error

undefined:4
    component:SomeComponent
              ^

ReferenceError: SomeComponent is not defined
    at eval (eval at <anonymous> (/home/ankush/makerobos/test-app/dist/prerender.js:119382:45), <anonymous>:4:15)
    at /home/ankush/makerobos/test-app/dist/prerender.js:119382:45
    at Array.forEach (<anonymous>)
    at /home/ankush/makerobos/test-app/dist/prerender.js:119361:49
    at Array.forEach (<anonymous>)
    at /home/ankush/makerobos/test-app/dist/prerender.js:119353:49
    at visitNode (/home/ankush/makerobos/test-app/dist/prerender.js:135564:24)
    at Object.forEachChild (/home/ankush/makerobos/test-app/dist/prerender.js:135866:24)
    at NodeObject.module.exports.NodeObject.forEachChild (/home/ankush/makerobos/test-app/dist/prerender.js:236085:23)
    at /home/ankush/makerobos/test-app/dist/prerender.js:119349:65
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! test-app@0.0.0 build:prerender: `npm run build:prod && node dist/prerender.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the test-app@0.0.0 build:prerender script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ankush/.npm/_logs/2019-05-14T11_20_39_598Z-debug.log
 

## Example repository

link to repo having this issue -> https://github.com/ank1106/ssr-test

**Comment by marcocoelho** [comment]
I'm going through a similar problem.

It runs all the process arrives at the end it displays the following message:


`WARNING in ./node_modules/typescript/lib/typescript.js 90061:19-45
Critical dependency: the request of a dependency is an expression
 @ ./prerender.ts
fs.js:122
    throw err;
    ^

Error: ENOENT: no such file or directory, open 'src/./app/../../shared-module/shared.module.ts'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:348:35)
    at D:\Projetos_Front\Marketplace.UI\dist\prerender.js:151189:40
    at Array.forEach (<anonymous>)
    at findRoutes (D:\Projetos_Front\Marketplace.UI\dist\prerender.js:151188:21)
    at D:\Projetos_Front\Marketplace.UI\dist\prerender.js:151189:26
    at Array.forEach (<anonymous>)
    at findRoutes (D:\Projetos_Front\Marketplace.UI\dist\prerender.js:151188:21)
    at D:\Projetos_Front\Marketplace.UI\dist\prerender.js:151189:26
    at Array.forEach (<anonymous>)`
