### ISSUE TITLE
Error when running prerender and using wildcard ** in routing since windows folder cant have that name

### ISSUE THREAD

**Issue by Fuzzy3** [maciejtreder/ng-toolkit#633]
## I'm submitting a...
<pre><code>
[x] Bug report 
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[x] @ng-toolkit/universal
[ ] @ng-toolkit/pwa
[ ] @ng-toolkit/firebug
</code></pre>

## Current behavior
When running prerender, the tool finds my different paths/routes and creates a folder for each path. However when it reaches the wildcard path ** it fails and complains about not being able to find the folder. I believe this is due to windows not allowing folders to be created with the name **.

Log:
<pre><code>
WARNING in ./node_modules/typescript/lib/typescript.js 94814:19-45
Critical dependency: the request of a dependency is an expression
 @ ./prerender.ts
Got following static routes:
/
And following found in the application:
/home
/bestilling
/om-os
/inspiration
/lejebetingelser
/samarbejdspartnere
/kontakt
/tak-for-din-bestilling
/loading
/**
fs.js:115
    throw err;
    ^

Error: ENOENT: no such file or directory, mkdir 'C:\Users\Line Oest Balmer\Desktop\Søren\jyskserviceudljeningDotDk\jyskserviceudlejning2\dist\static//**'
    at mkdirSync (fs.js:750:3)
    at C:\Users\Line Oest Balmer\Desktop\Søren\jyskserviceudljeningDotDk\jyskserviceudlejning2\dist\prerender.js:145530:69
    at Array.forEach (<anonymous>)
    at C:\Users\Line Oest Balmer\Desktop\Søren\jyskserviceudljeningDotDk\jyskserviceudlejning2\dist\prerender.js:145527:26
    at Array.forEach (<anonymous>)
    at Module.module.exports.__assign (C:\Users\Line Oest Balmer\Desktop\Søren\jyskserviceudljeningDotDk\jyskserviceudlejning2\dist\prerender.js:145522:11)
    at __webpack_require__ (C:\Users\Line Oest Balmer\Desktop\Søren\jyskserviceudljeningDotDk\jyskserviceudlejning2\dist\prerender.js:21:30)
    at C:\Users\Line Oest Balmer\Desktop\Søren\jyskserviceudljeningDotDk\jyskserviceudlejning2\dist\prerender.js:85:18
    at Object.<anonymous> (C:\Users\Line Oest Balmer\Desktop\Søren\jyskserviceudljeningDotDk\jyskserviceudlejning2\dist\prerender.js:88:10)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! jyskserviceudlejning2@0.0.0 build:prerender: `npm run build:prod && node dist/prerender.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the jyskserviceudlejning2@0.0.0 build:prerender script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
</code></pre>

## Expected behavior
I expect the prerender tool to work with wildcard paths like **.

## Minimal reproduction of the problem with instructions

1. ng new wildcardBugProj --routing
2. _edit routes file to contain a ** path_
3. npm run build:prerender

## Example repository

[https://github.com/Fuzzy3/jyskserviceudlejning2](https://github.com/Fuzzy3/jyskserviceudlejning2)

## What is the motivation / use case for changing the behavior?

Being able to prerender

## Environment

<pre><code>
Angular version: 8.0.2

- Node version: v10.13.0  
- Platform:  Windows 10

Others:
Tried with both git bash & powershell
</code></pre>

**Comment by Rangular1** [comment]
Hey,

Have you found a solution?  I have a similar error when using the @maciejtreder #ng-toolkit.  Please can someone help.

I am running "npm run build:prerender" and get this error:

WARNING in ./node_modules/typescript/lib/typescript.js 92165:19-45
Critical dependency: the request of a dependency is an expression
 @ ./prerender.ts
Got following static routes:
/
/about
And following found in the application:
fs.js:115
    throw err;
    ^

Error: EPERM: operation not permitted, copyfile './dist/browser/assets' -> './dist/static/assets'
    at Object.copyFileSync (fs.js:1724:3)
    at C:\Users\Owner\Desktop\boilerplate\dist\prerender.js:120051:12
    at Array.forEach (<anonymous>)
    at Module.module.exports.__assign (C:\Users\Owner\Desktop\boilerplate\dist\prerender.js:120049:14)
    at __webpack_require__ (C:\Users\Owner\Desktop\boilerplate\dist\prerender.js:21:30)
    at C:\Users\Owner\Desktop\boilerplate\dist\prerender.js:85:18
    at Object.<anonymous> (C:\Users\Owner\Desktop\boilerplate\dist\prerender.js:88:10)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! boilerplate@0.0.0 build:prerender: `npm run build:prod && node dist/prerender.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the boilerplate@0.0.0 build:prerender script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Owner\AppData\Roaming\npm-cache\_logs\2019-07-03T12_35_08_240Z-debug.log
PS C:\Users\Owner\Desktop\boilerplate> npm run build:prerender

> boilerplate@0.0.0 build:prerender C:\Users\Owner\Desktop\boilerplate
> npm run build:prod && node dist/prerender.js


> boilerplate@0.0.0 build:prod C:\Users\Owner\Desktop\boilerplate
> npm run build:ssr


> boilerplate@0.0.0 build:ssr C:\Users\Owner\Desktop\boilerplate
> npm run build:client-and-server-bundles && npm run compile:server


> boilerplate@0.0.0 build:client-and-server-bundles C:\Users\Owner\Desktop\boilerplate
> ng build --prod && ng run boilerplate:server:production


Date: 2019-07-03T13:08:39.387Z
Hash: 054a35a2ead851852e16
Time: 61945ms
chunk {0} runtime.26209474bfa8dc87a77c.js (runtime) 1.41 kB [entry] [rendered]
chunk {1} es2015-polyfills.bda95d5896422d031328.js (es2015-polyfills) 56.6 kB [initial] [rendered]
chunk {2} main.e76ea4e76c66bff59da6.js (main) 267 kB [initial] [rendered]
chunk {3} polyfills.8bbb231b43165d65d357.js (polyfills) 41 kB [initial] [rendered]
chunk {4} styles.3ff695c00d717f2d2a11.css (styles) 0 bytes [initial] [rendered]

Date: 2019-07-03T13:09:14.580Z
Hash: 8675ab14c509095b4d52
Time: 21313ms
chunk {main} main.js, main.js.map (main) 80.6 kB [entry] [rendered]

> boilerplate@0.0.0 compile:server C:\Users\Owner\Desktop\boilerplate
> webpack --config webpack.server.config.js --progress --colors

Hash: 2a5854b12379eab94904
Version: webpack 4.29.0
Time: 41187ms
Built at: 07/03/2019 2:10:01 PM
       Asset      Size  Chunks             Chunk Names
prerender.js  11.2 MiB       0  [emitted]  prerender
   server.js  5.12 MiB       1  [emitted]  server
Entrypoint server = server.js
Entrypoint prerender = prerender.js
  [1] ./node_modules/@angular/core/fesm5/core.js + 1 modules 969 KiB {0} {1} [built]
      |    2 modules
 [22] external "fs" 42 bytes {0} {1} [built]
 [25] external "path" 42 bytes {0} {1} [built]
 [52] external "url" 42 bytes {0} {1} [built]
 [68] ./node_modules/@angular/service-worker/fesm5/service-worker.js + 4 modules 17.1 KiB {0} {1} [built]
      |    5 modules
 [69] ./node_modules/@angular/platform-server/fesm5/platform-server.js + 1 modules 62.5 KiB {0} {1} [built]
      |    2 modules
 [72] external "buffer" 42 bytes {0} {1} [built]
 [92] external "crypto" 42 bytes {0} {1} [built]
 [94] external "events" 42 bytes {0} {1} [built]
 [95] ./src lazy namespace object 160 bytes {0} {1} [built]
[124] external "os" 42 bytes {0} {1} [built]
[155] ./dist/server/main.js 80.3 KiB {0} {1} [built]
[188] ./static.paths.ts 97 bytes {0} [built]
[265] ./prerender.ts 10.4 KiB {0} [built]
[278] ./server.ts + 1 modules 6.41 KiB {1} [built]
      | ./server.ts 1.42 KiB [built]
      |     + 1 hidden module
    + 382 hidden modules

WARNING in ./node_modules/typescript/lib/typescript.js 92165:19-45
Critical dependency: the request of a dependency is an expression
 @ ./prerender.ts
Got following static routes:
/
/about
And following found in the application:
fs.js:115
    throw err;
    ^

Error: EPERM: operation not permitted, copyfile './dist/browser/assets' -> './dist/static/assets'
    at Object.copyFileSync (fs.js:1724:3)
    at C:\Users\Owner\Desktop\boilerplate\dist\prerender.js:233118:12
    at Array.forEach (<anonymous>)
    at Module.<anonymous> (C:\Users\Owner\Desktop\boilerplate\dist\prerender.js:233116:14)
    at __webpack_require__ (C:\Users\Owner\Desktop\boilerplate\dist\prerender.js:21:30)
    at module.exports.extendStatics (C:\Users\Owner\Desktop\boilerplate\dist\prerender.js:85:18)
    at Object.<anonymous> (C:\Users\Owner\Desktop\boilerplate\dist\prerender.js:88:10)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! boilerplate@0.0.0 build:prerender: `npm run build:prod && node dist/prerender.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the boilerplate@0.0.0 build:prerender script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Owner\AppData\Roaming\npm-cache\_logs\2019-07-03T13_10_04_496Z-debug.log

**Comment by kapilbhagat2906** [comment]
Getting same error: 
EPERM: operation not permitted, copyfile './dist/browser/assets' -> './dist/static/assets'

**Comment by zzzoor** [comment]
Same error:
Error: EPERM: operation not permitted, copyfile './dist/browser/assets' -> './dist/static/assets'
Run command as administrator.

**Comment by kapilbhagat2906** [comment]
@zzzoor I got a fix for this solution and seems to be working fine now. For me, this issue occured as I further had folders in assets folder. Default prerender.ts code expects all files (no folder) within assets directory. To fix the issue, I updated prerender.ts to have additional checks for folders and iterate over all files in all folders in assets.
Please give it a try once.

**Comment by zzzoor** [comment]
@kapilbhagat2906 Yep, have sovled it using same solution. LOL. Thanks~
