### ISSUE TITLE
ng add @ng-toolkit/universal NOT WORKING GETTING ERROR

### ISSUE THREAD

**Issue by TousifMir** [maciejtreder/ng-toolkit#664]
When I am running this command 

> ng add @ng-toolkit/universal

I am getting below error: 

> Cannot find module '@schematics/angular/utility/dependencies'
> Error: Cannot find module '@schematics/angular/utility/dependencies'
>     at Function.Module._resolveFilename (module.js:547:15)
>     at Function.Module._load (module.js:474:25)
>     at Module.require (module.js:596:17)
>     at require (internal/module.js:11:18)
>     at Object.<anonymous> (C:\Projects\Practice\se0-test-2\ng-toolkit-master\ng-toolkit-master\application\node_modules\@ng-toolkit\universal\schematics.js:9:24)
>     at Module._compile (module.js:652:30)
>     at Object.Module._extensions..js (module.js:663:10)
>     at Module.load (module.js:565:32)
>     at tryModuleLoad (module.js:505:12)
>     at Function.Module._load (module.js:497:3)
>     at Module.require (module.js:596:17)
>     at require (internal/module.js:11:18)

Can you please tell me what & where the problem is? I tried in a new project as well but same issue in all the machines. SEO is a must requirement for my project but not able to use this beautiful toolkit. Please help in resolving this issue. Thank you so much in advance.

**Comment by KingDarBoja** [comment]
Does your project have `@angular-cli` dependency?

If not, please run `npm install -D @angular/cli`

Cheers!
