### ISSUE TITLE
Error: Cannot find module 'require("./server/main")'

### ISSUE THREAD

**Issue by ingluca888** [maciejtreder/ng-toolkit#733]
## I converted an existing Angular 8 App, I executed these without errors:
<pre><code>
•	Npm run ng add @ng-toolkit/universal
•	npm run build:prod

</code></pre>

## But when I run this:
<pre><code>
•	npm run server
</code></pre>

I get the following error:
Error: Cannot find module 'require("./server/main")'
Require stack:
- C:\Users\dist\server.js
- C:\Users\local.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:780:15)
    at Function.Module._load (internal/modules/cjs/loader.js:685:27)
    at Module.require (internal/modules/cjs/loader.js:838:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\Users\dist\server.js:25581:18)
    at __webpack_require__ (C:\Users\dist\server.js:21:30)
    at Module.<anonymous> (C:\Users\dist\server.js:125:90)
    at __webpack_require__ (C:\Users\dist\server.js:21:30)
    at C:\Users\dist\server.js:85:18
    at Object.<anonymous> (C:\Users\dist\server.js:88:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\dist\\server.js',
    'C:\\Users\\local.js'
  ]
}

**Comment by KingDarBoja** [comment]
Hello @ingluca888 

This bug is already known as per [this comment](https://github.com/maciejtreder/ng-toolkit/issues/729#issuecomment-557326881) will help you to fix it.
