### ISSUE TITLE
Unable to run server.js when using Apollo Graphql.

### ISSUE THREAD

**Issue by mmiedzianyy** [maciejtreder/ng-toolkit#736]
## I'm submitting a...
<pre><code>
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[x] @ng-toolkit/universal
[ ] @ng-toolkit/pwa
[ ] @ng-toolkit/firebug
</code></pre>

## Current behavior
I've installed "@ng-toolkit/universal": "^7.1.2 via ng add command.
My project is using Apollo Graphql. After fixing many issues and finally building application and the server I've encounter new error I can't fix.

`Error: Network error: 
    at new ApolloError (DIR\dist\server.js:176296:28)
    at PROJECT-DIR\dist\server.js:177478:40
    at PROJECT-DIR\dist\server.js:177790:25
    at Set.forEach (<anonymous>)
    at PROJECT-DIR\dist\server.js:177788:32
    at Map.forEach (<anonymous>)
    at QueryManager.module.exports.QueryManager.broadcastQueries (PROJECT-DIR\dist\server.js:177786:22)
    at PROJECT-DIR\dist\server.js:177392:47
    at ZoneDelegate.module.exports.ZoneDelegate.invoke (PROJECT-DIR\dist\server.js:534:26)
    at Object.onInvoke (DIR\dist\dist\server.js:27410:33)`

## Expected behavior
Install ng-toolkit/universal and run the SSR.

## Minimal reproduction of the problem with instructions
1. run `ng add ng add @ng-toolkit/universal@7.1.2`

## Environment

<pre><code>
Angular version: X.Y.Z

- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by mmiedzianyy** [comment]
I hope this issue relates to ng-toolkit.

**Comment by KingDarBoja** [comment]
Hello @mmiedzianyy,

You should update to the latest version of this package (8.0.3) and try again. Still gonna take a look at it as soon as possible.

Cheers!

**Comment by mmiedzianyy** [comment]
Hi @KingDarBoja.
I'm cursed or what..
Upgrading to 8.0.3 didn't help. 
Installing fresh version in freshly created project resulted with this error:
`Cannot read property 'kind' of undefined`.

Should I make another issue? :/

**Comment by KingDarBoja** [comment]
> Hi @KingDarBoja.
> I'm cursed or what..
> Upgrading to 8.0.3 didn't help.
> Installing latest (8.0.3) version in freshly created project resulted with this error:
> `Cannot read property 'kind' of undefined`.
> 
> Should I make another issue? :/

Hard to tell where this error comes from, can you share your repo in order to checkout what's going on? Or if you are too lazy, you could use my [Angular Serverless Sample](https://github.com/KingDarBoja/Angular-serverless-sample) repo and start from it.

**Comment by mmiedzianyy** [comment]
I can't share the repository.
But I'll try to reproduce it and share with you.

**Comment by KingDarBoja** [comment]
The upcoming version should bring a better logging for these cases. I am willing to look at this issue after new year 👍

**Comment by mmiedzianyy** [comment]
So I've installed Apollo Angular on your sample but there were no problems with graphql. I was trying to mess with the application as much as I could but with no chance of reproducing my existing problem..
Original project is under NDA so I can't share the code with you but to try and find it myself.
I guess I will end up building the app on top of your starter project or similar one inspired by it.

**Comment by KingDarBoja** [comment]
Glad to know the sample project helped you.

Also, I am going to add `serverless-offline` package on the example project so users can test locally their lambda functions so maybe you will be interested on such feature too.

And forgot to mention, you tested it on deployment with GraphQL stuff? I am looking forward for testing it too as long as I get some free time so the example can be multipurpose for anyone interested.

Cheers!

**Comment by mmiedzianyy** [comment]
Good to know, thanks!

Yeah. Both local and deployment works just fine with graphql. 
I'll share the repo under this post on monday. There is separate graphql module created with extra options added.

**Comment by mmiedzianyy** [comment]
Hello,
I've created the [repo for a project](https://github.com/mmiedzianyy/example-angular-ng-toolkit_n_apollo-graphql) based on your sample.
