### ISSUE TITLE
I am getting the below error when i run npm run build:prerender

### ISSUE THREAD

**Issue by navin10sharma** [maciejtreder/ng-toolkit#749]
fs.js:114
    throw err;
    ^

Error: ENOENT: no such file or directory, open 'src/@nguniversal/module-map-ngfactory-loader.ts'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:343:35)
    at eval (webpack:///./prerender.ts?:80:29)
    at Module../prerender.ts (/Users/pietech/Desktop/Projects/Web-Projects/get-flutter-website/dist/prerender.js:3463:1)
    at __webpack_require__ (/Users/pietech/Desktop/Projects/Web-Projects/get-flutter-website/dist/prerender.js:21:30)
    at /Users/pietech/Desktop/Projects/Web-Projects/get-flutter-website/dist/prerender.js:85:18
    at Object.<anonymous> (/Users/pietech/Desktop/Projects/Web-Projects/get-flutter-website/dist/prerender.js:88:10)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! kilian-ng@0.0.0 build:prerender: `npm run build:prod && node dist/prerender.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the kilian-ng@0.0.0 build:prerender script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/pietech/.npm/_logs/2020-01-03T07_07_26_062Z-debug.log

**Comment by KingDarBoja** [comment]
Hello @navin10sharma 

Which `angular` and `@ng-toolkit` version are you using? Can you share the reproduction steps too?

**Comment by abhishekdarteweb** [comment]
Hello,

I am getting same error did you find any solution for it?

**Comment by navin10sharma** [comment]
Angular cli version 8.3.8 and "@ng-toolkit/universal": "^8.0.3",

**Comment by KingDarBoja** [comment]
Can you guys copy the contents of `prerender.ts`, `main.ts`, `main.server.ts` and `server.ts` from this [working example repo](https://github.com/KingDarBoja/example-angular-ng-toolkit) and try again?
