### ISSUE TITLE
Angular pre-rendering error

### ISSUE THREAD

**Issue by abhishekdarteweb** [maciejtreder/ng-toolkit#753]
Getting Error when run  **npm run build:prerender** command

[416] ./static.paths.ts 71 bytes {1} [built]
    + 403 hidden modules
fs.js:114
    throw err;
    ^

Error: ENOENT: no such file or directory, open 'src/@nguniversal/module-map-ngfactory-loader.ts'
    at Object.openSync (fs.js:438:3)
    at Object.readFileSync (fs.js:343:35)
    at Module.<anonymous> (E:\angular\nk\dist\prerender.js:138297:29)
    at __webpack_require__ (E:\angular\nk\dist\prerender.js:21:30)
    at E:\angular\nk\dist\prerender.js:85:18
    at Object.<anonymous> (E:\angular\nk\dist\prerender.js:88:10)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nk@0.0.0 build:prerender: `npm run build:prod && node dist/prerender.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nk@0.0.0 build:prerender script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Abhishek\AppData\Roaming\npm-cache\_logs\2020-01-07T06_36_42_545Z-debug.log

**Comment by KingDarBoja** [comment]
Please take a look at #754.
