### ISSUE TITLE
error: npm run build:prerender

### ISSUE THREAD

**Issue by tkau87** [maciejtreder/ng-toolkit#754]
## I'm submitting a...

<pre><code>
[ ] Bug report  
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/universal
</code></pre>

## Current behavior
everything works well when creating initial new angular project with CLI. But when i add components + modules + lazy loaded module, prerender build does not work anymore.

## Expected behavior
Build prerender to be working with angular 8 web app.

## Minimal reproduction of the problem with instructions
step 1) npm run build:prerender
step 2) output error: 

<pre><code>
fs.js:114
    throw err;
    ^

Error: ENOENT: no such file or directory, open 'src/./app/./core-routing.module.ts'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:343:35)
    at identifiers.forEach.identifier (C:\Users\sgtra\Desktop\assia\appWorkspace\WEBSITE\akcws02\artkauric-ssr\dist\prerender.js:129207:42)
    at Array.forEach (<anonymous>)
    at findRoutes (C:\Users\sgtra\Desktop\assia\appWorkspace\WEBSITE\akcws02\artkauric-ssr\dist\prerender.js:129206:21)
    at identifiers.forEach.identifier (C:\Users\sgtra\Desktop\assia\appWorkspace\WEBSITE\akcws02\artkauric-ssr\dist\prerender.js:129207:28)
    at Array.forEach (<anonymous>)
    at findRoutes (C:\Users\sgtra\Desktop\assia\appWorkspace\WEBSITE\akcws02\artkauric-ssr\dist\prerender.js:129206:21)
    at identifiers.forEach.identifier (C:\Users\sgtra\Desktop\assia\appWorkspace\WEBSITE\akcws02\artkauric-ssr\dist\prerender.js:129207:28)
    at Array.forEach (<anonymous>)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! artkauric-ssr@0.0.0 build:prerender: `npm run build:prod && node dist/prerender.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the artkauric-ssr@0.0.0 build:prerender script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\****\AppData\Roaming\npm-cache\_logs\2020-01-07T06_47_22_870Z-debug.log
</pre></code>

This is my lazy loaded module where it seems to have a problem finding the file:

<pre><code>
export const routes: Routes = [
  { path: '', pathMatch: 'full', redirectTo: 'coming-soon' },
  {
    path: 'coming-soon',
    loadChildren: () => import('./core/core.module').then(m => m.CoreModule)
  },
];
</pre></code>

It looks like the webpack is fetching the complete path './core/core.module' instead of 'core/core.module' and is doing the same with './app' instead of 'app'

## Environment

<pre><code>
Angular version: 8
- Node version: 6
- Platform:  windows
</pre></code>

**Comment by KingDarBoja** [comment]
Update to latest version of `@ng-toolkit/universal` (should be 8.0.3).

**Comment by tkau87** [comment]
I get the following error with @ng-toolkit/universal (should be 8.0.3).

<pre><code>
fs.js:114
    throw err;
    ^

Error: ENOENT: no such file or directory, open 'src/@nguniversal/module-map-ngfactory-loader.ts'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:343:35)
    at Module.<anonymous> (C:\Users\sgtra\Desktop\assia\appWorkspace\WEBSITE\akcws02\artkauric-ng-ssr\dist\prerender.js:2846:29)
    at __webpack_require__ (C:\Users\sgtra\Desktop\assia\appWorkspace\WEBSITE\akcws02\artkauric-ng-ssr\dist\prerender.js:21:30)
    at C:\Users\sgtra\Desktop\assia\appWorkspace\WEBSITE\akcws02\artkauric-ng-ssr\dist\prerender.js:85:18
    at Object.<anonymous> (C:\Users\sgtra\Desktop\assia\appWorkspace\WEBSITE\akcws02\artkauric-ng-ssr\dist\prerender.js:88:10)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! artkauric-ng-ssr@0.0.0 build:prerender: `npm run build:prod && node dist/prerender.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the artkauric-ng-ssr@0.0.0 build:prerender script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\sgtra\AppData\Roaming\npm-cache\_logs\2020-01-08T12_56_43_865Z-debug.log
</pre></code>

**Comment by KingDarBoja** [comment]
Good to know, it is related to the prerendering script as this isn't working right now.

Please copy the content of [this prerender](https://github.com/KingDarBoja/example-angular-ng-toolkit/blob/master/prerender.ts) file from my working sample repo.

**Comment by sukhminderx** [comment]
Using version 8.0.3 and copied the mentioned files from working sample repo.
Lazy loaded modules are giving this error:
![image](https://user-images.githubusercontent.com/35064031/79060510-d7a0f080-7c53-11ea-9681-2a20c3cec1b0.png)

Is it related to this "it is related to the prerendering script as this isn't working right now" or something else?

**Comment by sukhminderx** [comment]
Adding:
with the above changes, the ssr command npm run serve:ssr fails with this:

server.app.listen(port, () => {
           ^

TypeError: Cannot read property 'listen' of undefined

**Comment by KingDarBoja** [comment]
Can you use 8.1.0 version instead? :D

**Comment by sukhminderx** [comment]
sure thing, I'll test it. :)
