### ISSUE TITLE
Browser build not found (lack of entry with build-angular:browser builder) in angular.json

### ISSUE THREAD

**Issue by LukasDoesDev** [maciejtreder/ng-toolkit#798]
## I'm submitting a...

<pre><code>
[x] Bug report  
[  ] Feature request
[  ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[x] @ng-toolkit/serverless
[] @ng-toolkit/universal
[ ] @ng-toolkit/pwa
[ ] @ng-toolkit/firebug
</code></pre>

## Current behavior

When i run
`ng add @ng-toolkit/serverless --provider aws`,
it prints
<pre><code>
Skipping installation: Package already installed
[bugsnag] Loaded!
[bugsnag] Loaded!
ERROR MESSAGE: Browser build not found (lack of entry with build-angular:browser builder) in angular.json
ERROR STACKTRACE: Error: Browser build not found (lack of entry with build-angular:browser builder) in angular.json
    at Object.getBrowserDistFolder (D:\CodingProjects\devZeta\frontEnd\node_modules\@ng-toolkit\serverless\node_modules\@ng-toolkit\_utils\index.js:343:11)
    at D:\CodingProjects\devZeta\frontEnd\node_modules\@ng-toolkit\serverless\src\index.js:151:64
    at MergeMapSubscriber.project (D:\CodingProjects\devZeta\frontEnd\node_modules\@ng-toolkit\serverless\node_modules\@angular-devkit\schematics\src\rules\call.js:74:24)
    at MergeMapSubscriber._tryNext (D:\CodingProjects\devZeta\frontEnd\node_modules\@ng-toolkit\serverless\node_modules\rxjs\internal\operators\mergeMap.js:69:27)     
    at MergeMapSubscriber._next (D:\CodingProjects\devZeta\frontEnd\node_modules\@ng-toolkit\serverless\node_modules\rxjs\internal\operators\mergeMap.js:59:18)        
    at MergeMapSubscriber.Subscriber.next (D:\CodingProjects\devZeta\frontEnd\node_modules\@ng-toolkit\serverless\node_modules\rxjs\internal\Subscriber.js:66:18)      
    at MergeMapSubscriber.notifyNext (D:\CodingProjects\devZeta\frontEnd\node_modules\@ng-toolkit\serverless\node_modules\rxjs\internal\operators\mergeMap.js:92:26)   
    at InnerSubscriber._next (D:\CodingProjects\devZeta\frontEnd\node_modules\@ng-toolkit\serverless\node_modules\rxjs\internal\InnerSubscriber.js:28:21)
    at InnerSubscriber.Subscriber.next (D:\CodingProjects\devZeta\frontEnd\node_modules\@ng-toolkit\serverless\node_modules\rxjs\internal\Subscriber.js:66:18)
    at TapSubscriber._next (D:\CodingProjects\devZeta\frontEnd\node_modules\@ng-toolkit\serverless\node_modules\rxjs\internal\operators\tap.js:65:26)
    at TapSubscriber.Subscriber.next (D:\CodingProjects\devZeta\frontEnd\node_modules\@ng-toolkit\serverless\node_modules\rxjs\internal\Subscriber.js:66:18)
    at TapSubscriber._next (D:\CodingProjects\devZeta\frontEnd\node_modules\@ng-toolkit\serverless\node_modules\rxjs\internal\operators\tap.js:65:26)
    at TapSubscriber.Subscriber.next (D:\CodingProjects\devZeta\frontEnd\node_modules\@ng-toolkit\serverless\node_modules\rxjs\internal\Subscriber.js:66:18)
    at TakeLastSubscriber._complete (D:\CodingProjects\devZeta\frontEnd\node_modules\@ng-toolkit\serverless\node_modules\rxjs\internal\operators\takeLast.js:71:29)    
    at TakeLastSubscriber.Subscriber.complete (D:\CodingProjects\devZeta\frontEnd\node_modules\@ng-toolkit\serverless\node_modules\rxjs\internal\Subscriber.js:78:18)  
    at DefaultIfEmptySubscriber._complete (D:\CodingProjects\devZeta\frontEnd\node_modules\@ng-toolkit\serverless\node_modules\rxjs\internal\operators\defaultIfEmpty.js:47:26)
ERROR TIP: If you think that this error shouldn't occur, please fill up bug report here: https://github.com/maciejtreder/ng-toolkit/issues/new
INFO: stacktrace has been sent to tracking system.
Nothing to be done.
</code></pre>

## Expected behavior

The command would finish without an error. :D

## Minimal reproduction of the problem with instructions

Uhhh... My project is super big...

## Example repository

Sorry, i don't have a repo for this project.

## What is the motivation / use case for changing the behavior?

What does this mean?

## Environment

<pre><code>
Angular version: 9.0.7

- Node version: v13.11.0 
- Platform:  Windows 10 Pro v1903

Others:

I have a custom builder in angular.json.

angular.json:

{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "newProjectRoot": "projects",
  "projects": {
    "devZeta": {
      "projectType": "application",
      "schematics": {
        "@schematics/angular:component": {
          "style": "scss"
        }
      },
      "root": "",
      "sourceRoot": "src",
      "prefix": "app",
      "architect": {
        "build": {
          "builder": "@angular-builders/custom-webpack:browser",
          "options": {
            "browserTarget": "devZeta:build",
            "outputPath": "dist/devZeta",
            "index": "src/index.html",
            "main": "src/main.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "tsconfig.app.json",
            "aot": true,
            "assets": [
              "src/favicon.ico",
              "src/assets"
            ],
            "styles": [
              "src/styles.scss"
            ],
            "scripts": [],

            "customWebpackConfig": {
              "path": "./webpack.config.js"
            },
            "serviceWorker": true,
            "ngswConfigPath": "ngsw-config.json"
          }
        },
        "serve": {
          "builder": "@angular-builders/custom-webpack:dev-server",
          "options": {
            "browserTarget": "devZeta:build",
            "customWebpackConfig": {
              "path": "./webpack.config.js"
            }
          }
        },
        "extract-i18n": {
          "builder": "@angular-devkit/build-angular:extract-i18n",
          "options": {
            "browserTarget": "devZeta:build"
          }
        },
        "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "main": "src/test.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "tsconfig.spec.json",
            "karmaConfig": "karma.conf.js",
            "assets": [
              "src/favicon.ico",
              "src/assets",
              "src/manifest.webmanifest"
            ],
            "styles": [
              "src/styles.scss"
            ],
            "scripts": []
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": [
              "tsconfig.app.json",
              "tsconfig.spec.json",
              "e2e/tsconfig.json"
            ],
            "exclude": [
              "**/node_modules/**"
            ]
          }
        },
        "e2e": {
          "builder": "@angular-devkit/build-angular:protractor",
          "options": {
            "protractorConfig": "e2e/protractor.conf.js",
            "devServerTarget": "devZeta:serve"
          },
          "configurations": {
            "production": {
              "devServerTarget": "devZeta:serve:production"
            }
          }
        }
      }
    }},
  "defaultProject": "devZeta"
}
</code></pre>

**Comment by LukasDoesDev** [comment]
Updated to Angular `9.1.3`
<pre><code>Angular CLI: 9.1.3
Node: 13.11.0
OS: win32 x64</code></pre>

**Comment by LukasDoesDev** [comment]
Fixed it by using original angular.json... But now i don't have tailwindcss...
