### ISSUE TITLE
Error: You must pass in a NgModule or NgModuleFactory to be bootstrapped

### ISSUE THREAD

**Issue by Sangram9693** [maciejtreder/ng-toolkit#827]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[ ] @ng-toolkit/universal
[ ] @ng-toolkit/pwa
[ ] @ng-toolkit/firebug
</code></pre>

## Current behavior
> bolg-almightytricks@0.0.0 server D:\sangram\mywebsite\bolg-almightytricks
> node local.js

Listening on: http://localhost:4000
Error: You must pass in a NgModule or NgModuleFactory to be bootstrapped
    at View.engine (D:\sangram\mywebsite\bolg-almightytricks\dist\server\main.js:1:1179115)
    at View.render (D:\sangram\mywebsite\bolg-almightytricks\dist\server.js:17191:8)
    at tryRender (D:\sangram\mywebsite\bolg-almightytricks\dist\server.js:12424:10)
    at Function.render (D:\sangram\mywebsite\bolg-almightytricks\dist\server.js:12376:3)
    at ServerResponse.render (D:\sangram\mywebsite\bolg-almightytricks\dist\server.js:24788:7)
    at D:\sangram\mywebsite\bolg-almightytricks\dist\server.js:143:9
    at Layer.handle [as handle_request] (D:\sangram\mywebsite\bolg-almightytricks\dist\server.js:15808:5)
    at next (D:\sangram\mywebsite\bolg-almightytricks\dist\server.js:14729:13)
    at Route.dispatch (D:\sangram\mywebsite\bolg-almightytricks\dist\server.js:14704:3)
    at Layer.handle [as handle_request] (D:\sangram\mywebsite\bolg-almightytricks\dist\server.js:15808:5)

## Expected behavior
It should return valid web page

## Environment

<pre><code>
Angular version: X.Y.Z

- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by atif-shamim** [comment]
I am also facing same issue
