### ISSUE TITLE
ERROR MESSAGE: Path "/server.ts" already exist.

### ISSUE THREAD

**Issue by progtarek** [maciejtreder/ng-toolkit#846]
## I'm getting this error when I am trying to run "ng add @ng-toolkit/serverless --provider aws" on a new Angular 11.0.1 project.

ERROR STACKTRACE: Error: Path "/server.ts" already exist.
    at SwitchMapSubscriber.project (D:\qurba\qurba-code\qurba-client\new\qurba\node_modules\@angular-devkit\core\src\virtual-fs\host\record.js:209:42)
    at SwitchMapSubscriber._next (D:\qurba\qurba-code\qurba-client\new\qurba\node_modules\rxjs\internal\operators\switchMap.js:47:27)
    at SwitchMapSubscriber.Subscriber.next (D:\qurba\qurba-code\qurba-client\new\qurba\node_modules\rxjs\internal\Subscriber.js:66:18)
    at DefaultIfEmptySubscriber._next (D:\qurba\qurba-code\qurba-client\new\qurba\node_modules\rxjs\internal\operators\defaultIfEmpty.js:41:26)
    at DefaultIfEmptySubscriber.Subscriber.next (D:\qurba\qurba-code\qurba-client\new\qurba\node_modules\rxjs\internal\Subscriber.js:66:18)
    at TakeLastSubscriber._complete (D:\qurba\qurba-code\qurba-client\new\qurba\node_modules\rxjs\internal\operators\takeLast.js:71:29)
    at TakeLastSubscriber.Subscriber.complete (D:\qurba\qurba-code\qurba-client\new\qurba\node_modules\rxjs\internal\Subscriber.js:78:18)
    at ScanSubscriber.Subscriber._complete (D:\qurba\qurba-code\qurba-client\new\qurba\node_modules\rxjs\internal\Subscriber.js:96:26)
    at ScanSubscriber.Subscriber.complete (D:\qurba\qurba-code\qurba-client\new\qurba\node_modules\rxjs\internal\Subscriber.js:78:18)
    at MergeMapSubscriber._complete (D:\qurba\qurba-code\qurba-client\new\qurba\node_modules\rxjs\internal\operators\mergeMap.js:88:30)
    at MergeMapSubscriber.Subscriber.complete (D:\qurba\qurba-code\qurba-client\new\qurba\node_modules\rxjs\internal\Subscriber.js:78:18)
    at Observable._subscribe (D:\qurba\qurba-code\qurba-client\new\qurba\node_modules\rxjs\internal\util\subscribeToArray.js:7:16)
    at Observable._trySubscribe (D:\qurba\qurba-code\qurba-client\new\qurba\node_modules\rxjs\internal\Observable.js:44:25)
    at Observable.subscribe (D:\qurba\qurba-code\qurba-client\new\qurba\node_modules\rxjs\internal\Observable.js:30:22)
    at MergeMapOperator.call (D:\qurba\qurba-code\qurba-client\new\qurba\node_modules\rxjs\internal\operators\mergeMap.js:37:23)
    at Observable.subscribe (D:\qurba\qurba-code\qurba-client\new\qurba\node_modules\rxjs\internal\Observable.js:25:31)
<pre><code>
[ * ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre>ng add @ng-toolkit/serverless --provider aws<code>
[ ] @ng-toolkit/init
[ * ] @ng-toolkit/serverless
[ ] @ng-toolkit/universal
[ ] @ng-toolkit/pwa
[ ] @ng-toolkit/firebug
</code></pre>

## Minimal reproduction of the problem with instructions
I created new project then try to run "ng add @ng-toolkit/serverless --provider aws"

## Environment

<pre><code>
Angular version: 11.0.1

- Node version: 12
- Platform:  Windows 

Others:

</code></pre>

**Comment by Zaklinatel** [comment]
Same problem here
