### ISSUE TITLE
I don't know what's wrong with this comand

### ISSUE THREAD

**Issue by kode-mafia** [maciejtreder/ng-toolkit#887]
╰─λ ng add @ng-toolkit/serverless --provider aws
Skipping installation: Package already installed
[bugsnag] Loaded!
"ng-toolkit serverless" schema is using the keyword "id" which its support is deprecated. Use "$id" for schema ID.
ERROR MESSAGE: Path "/server.ts" already exist.
ERROR STACKTRACE: Error: Path "/server.ts" already exist.
    at SwitchMapSubscriber.project (/home/kodemafia/angular/skin/node_modules/@angular-devkit/core/src/virtual-fs/host/record.js:220:42)
    at SwitchMapSubscriber._next (/home/kodemafia/angular/skin/node_modules/rxjs/internal/operators/switchMap.js:47:27)
    at SwitchMapSubscriber.Subscriber.next (/home/kodemafia/angular/skin/node_modules/rxjs/internal/Subscriber.js:66:18)
    at DefaultIfEmptySubscriber._next (/home/kodemafia/angular/skin/node_modules/rxjs/internal/operators/defaultIfEmpty.js:41:26)
    at DefaultIfEmptySubscriber.Subscriber.next (/home/kodemafia/angular/skin/node_modules/rxjs/internal/Subscriber.js:66:18)
    at TakeLastSubscriber._complete (/home/kodemafia/angular/skin/node_modules/rxjs/internal/operators/takeLast.js:71:29)
    at TakeLastSubscriber.Subscriber.complete (/home/kodemafia/angular/skin/node_modules/rxjs/internal/Subscriber.js:78:18)
    at ScanSubscriber.Subscriber._complete (/home/kodemafia/angular/skin/node_modules/rxjs/internal/Subscriber.js:96:26)
    at ScanSubscriber.Subscriber.complete (/home/kodemafia/angular/skin/node_modules/rxjs/internal/Subscriber.js:78:18)
    at MergeMapSubscriber._complete (/home/kodemafia/angular/skin/node_modules/rxjs/internal/operators/mergeMap.js:88:30)
    at MergeMapSubscriber.Subscriber.complete (/home/kodemafia/angular/skin/node_modules/rxjs/internal/Subscriber.js:78:18)
    at Observable._subscribe (/home/kodemafia/angular/skin/node_modules/rxjs/internal/util/subscribeToArray.js:7:16)
    at Observable._trySubscribe (/home/kodemafia/angular/skin/node_modules/rxjs/internal/Observable.js:44:25)
    at Observable.subscribe (/home/kodemafia/angular/skin/node_modules/rxjs/internal/Observable.js:30:22)
    at MergeMapOperator.call (/home/kodemafia/angular/skin/node_modules/rxjs/internal/operators/mergeMap.js:37:23)
    at Observable.subscribe (/home/kodemafia/angular/skin/node_modules/rxjs/internal/Observable.js:25:31)
ERROR TIP: If you think that this error shouldn't occur, please fill up bug report here: https://github.com/maciejtreder/ng-toolkit/issues/new
INFO: stacktrace has been sent to tracking system.
Nothing to be done.

**Comment by AlexTech314** [comment]
I am having the same issue:

PS C:\Users\Alex\ng-doc-pipeline\doc-onboarding-ui> ng add @ng-toolkit/serverless --provider aws
Skipping installation: Package already installed
[bugsnag] Loaded!
An unhandled exception occurred: NOT SUPPORTED: keyword "id", use "$id" for schema ID
See "C:\Users\Alex\AppData\Local\Temp\ng-wkSUmx\angular-errors.log" for further details.

Here is my versioning:
PS C:\Users\Alex\ng-doc-pipeline\doc-onboarding-ui> ng --version

Angular CLI: 13.1.3
Node: 16.13.0
Package Manager: npm 8.3.1
OS: win32 x64

Angular: 13.1.2
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1301.3
@angular-devkit/build-angular   13.1.3
@angular-devkit/core            13.1.3
@angular-devkit/schematics      13.1.3
@angular/cdk                    13.0.0
@angular/cli                    13.1.3
@angular/material               13.0.0
@nguniversal/builders           13.0.1
@nguniversal/express-engine     13.0.1
@schematics/angular             13.1.3
rxjs                            7.4.0
typescript                      4.4.4

**Comment by eriklive** [comment]
Any update on that?
